-- GENERATED by migrations/neon/generate_schema.py - do not hand-edit.
-- Regenerate after changing any Beanie model.
CREATE SCHEMA IF NOT EXISTS app;
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- User
CREATE TABLE IF NOT EXISTS app.users (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , email text
    , hashed_password text
    , full_name text
    , username text
    , account_type text
    , auth_provider text
    , is_active boolean
    , is_admin boolean
    , totp_enabled boolean
    , totp_secret_encrypted text
    , profile_embedding double precision[] DEFAULT '{}'
    , profile_embedding_model_version text
    , profile_embedding_updated_at timestamptz
    , profile_embedding_interaction_count bigint
    , created_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);

-- Post
CREATE TABLE IF NOT EXISTS app.posts (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , user_id text
    , domain text
    , content text
    , likes_count bigint
    , created_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);

-- Comment
CREATE TABLE IF NOT EXISTS app.comments (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , post_id text
    , user_id text
    , content text
    , created_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);

-- Profile
CREATE TABLE IF NOT EXISTS app.profiles (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , user_id text
    , account_type text
    , first_name text
    , last_name text
    , mobile text
    , country_code text
    , user_type text
    , domain text
    , course text
    , course_specialization text
    , passout_year bigint
    , class_grade bigint
    , current_job_role text
    , total_work_experience text
    , experience_summary text
    , college_name text
    , company_name text
    , company_website text
    , company_size text
    , company_description text
    , hiring_for text
    , goals text[] DEFAULT '{}'
    , career_intent text[] DEFAULT '{}'
    , domains_of_interest text[] DEFAULT '{}'
    , preferred_roles text
    , preferred_locations text
    , preferred_work_mode text
    , work_preferences text[] DEFAULT '{}'
    , expected_stipend_range text
    , expected_stipend_min bigint
    , expected_stipend_max bigint
    , availability text
    , graduation_year bigint
    , opportunity_types text[] DEFAULT '{}'
    , pan_india boolean
    , prefer_wfh boolean
    , consent_data_processing boolean
    , consent_updates boolean
    , consent_data_processing_at timestamptz
    , consent_policy_version text
    , consent_withdrawn_at timestamptz
    , onboarding_step text
    , onboarding_completed boolean
    , onboarding_completed_at timestamptz
    , onboarding_prompt_seen boolean
    , onboarding_first_seen_at timestamptz
    , bio text
    , skills text
    , interests text
    , interest_graph text[] DEFAULT '{}'
    , achievements text
    , education text
    , certificates text
    , projects text
    , responsibilities text
    , current_address_region text
    , permanent_address_region text
    , hobbies text[] DEFAULT '{}'
    , social_links jsonb DEFAULT '{}'::jsonb
    , resume_url text
    , resume_filename text
    , resume_content_type text
    , resume_storage_key text
    , resume_uploaded_at timestamptz
    , cold_start_quality_score double precision
    , cold_start_strategy text
    , preference_embedding double precision[] DEFAULT '{}'
    , preference_embedding_model_version text
    , preference_embedding_updated_at timestamptz
    , persona_cluster_id bigint
    , taste_calibration_count bigint
    , incoscore double precision
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS profiles_account_type_persona_cluster_id_idx ON app.profiles (account_type ASC, persona_cluster_id ASC);
CREATE INDEX IF NOT EXISTS profiles_cold_start_strategy_cold_start_quality_score_idx ON app.profiles (cold_start_strategy ASC, cold_start_quality_score DESC);

-- OpportunityInteraction
CREATE TABLE IF NOT EXISTS app.opportunity_interactions (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , user_id text
    , opportunity_id text
    , interaction_type jsonb DEFAULT '{}'::jsonb
    , event_type jsonb DEFAULT '{}'::jsonb
    , reward double precision
    , dwell_time_ms bigint
    , scroll_depth double precision
    , referrer_rank bigint
    , session_id text
    , exposure_id text
    , feature_snapshot_id text
    , opportunity_version_id text
    , feedback_reason text
    , randomized_exposure boolean
    , exploration_probability double precision
    , cold_start boolean
    , ranking_mode jsonb DEFAULT '{}'::jsonb
    , experiment_key text
    , experiment_variant text
    , query text
    , model_version_id text
    , rank_position bigint
    , match_score double precision
    , features jsonb DEFAULT '{}'::jsonb
    , traffic_type jsonb DEFAULT '{}'::jsonb
    , created_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS opportunity_interactions_traffic_type_created_at_idx ON app.opportunity_interactions (traffic_type ASC, created_at DESC);
CREATE INDEX IF NOT EXISTS opportunity_interactions_user_id_created_at_idx ON app.opportunity_interactions (user_id ASC, created_at DESC);
CREATE INDEX IF NOT EXISTS opportunity_interactions_opportunity_id_created_at_idx ON app.opportunity_interactions (opportunity_id ASC, created_at DESC);
CREATE INDEX IF NOT EXISTS opportunity_interactions_experiment_key_experiment_variant_t ON app.opportunity_interactions (experiment_key ASC, experiment_variant ASC, traffic_type ASC, created_at DESC);
CREATE INDEX IF NOT EXISTS opportunity_interactions_event_type_created_at_idx ON app.opportunity_interactions (event_type ASC, created_at DESC);

-- RecommendationSession
CREATE TABLE IF NOT EXISTS app.recommendation_sessions (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , session_id text
    , user_id text
    , started_at timestamptz
    , last_activity_at timestamptz
    , ended_at timestamptz
    , device_type text
    , platform text
    , country_code text
    , network_type text
    , logged_in boolean
    , total_results bigint
    , query text
    , sort text
    , filters jsonb DEFAULT '{}'::jsonb
    , entry_source text
    , previous_session_gap_seconds bigint
    , experiment_key text
    , experiment_variant text
    , traffic_type jsonb DEFAULT '{}'::jsonb
    , created_at timestamptz
    , updated_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS recommendation_sessions_session_id_idx ON app.recommendation_sessions (session_id ASC);
CREATE INDEX IF NOT EXISTS recommendation_sessions_user_id_last_activity_at_idx ON app.recommendation_sessions (user_id ASC, last_activity_at DESC);

-- RecommendationExposure
CREATE TABLE IF NOT EXISTS app.recommendation_exposures (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , exposure_id text
    , session_id text
    , user_id text
    , opportunity_id text
    , opportunity_version_id text
    , feature_snapshot_id text
    , ranking_mode text
    , experiment_key text
    , experiment_variant text
    , model_version_id text
    , rank_position bigint
    , match_score double precision
    , randomized_exposure boolean
    , exploration_probability double precision
    , query text
    , filter_fingerprint text
    , traffic_type jsonb DEFAULT '{}'::jsonb
    , served_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS recommendation_exposures_exposure_id_idx ON app.recommendation_exposures (exposure_id ASC);
CREATE INDEX IF NOT EXISTS recommendation_exposures_user_id_opportunity_id_served_at_id ON app.recommendation_exposures (user_id ASC, opportunity_id ASC, served_at DESC);
CREATE INDEX IF NOT EXISTS recommendation_exposures_session_id_rank_position_idx ON app.recommendation_exposures (session_id ASC, rank_position ASC);

-- RecommendationFeatureSnapshot
CREATE TABLE IF NOT EXISTS app.recommendation_feature_snapshots (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , snapshot_id text
    , snapshot_hash text
    , user_id text
    , opportunity_id text
    , opportunity_version_id text
    , feature_schema_version text
    , model_version_id text
    , profile_snapshot jsonb DEFAULT '{}'::jsonb
    , opportunity_snapshot jsonb DEFAULT '{}'::jsonb
    , features jsonb DEFAULT '{}'::jsonb
    , captured_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS recommendation_feature_snapshots_snapshot_id_idx ON app.recommendation_feature_snapshots (snapshot_id ASC);
CREATE INDEX IF NOT EXISTS recommendation_feature_snapshots_snapshot_hash_idx ON app.recommendation_feature_snapshots (snapshot_hash ASC);

-- OpportunityVersion
CREATE TABLE IF NOT EXISTS app.opportunity_versions (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , version_id text
    , opportunity_id text
    , version_number bigint
    , content_hash text
    , snapshot jsonb DEFAULT '{}'::jsonb
    , captured_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS opportunity_versions_version_id_idx ON app.opportunity_versions (version_id ASC);
CREATE INDEX IF NOT EXISTS opportunity_versions_opportunity_id_content_hash_idx ON app.opportunity_versions (opportunity_id ASC, content_hash ASC);
CREATE INDEX IF NOT EXISTS opportunity_versions_opportunity_id_version_number_idx ON app.opportunity_versions (opportunity_id ASC, version_number DESC);

-- RecommendationFeedback
CREATE TABLE IF NOT EXISTS app.recommendation_feedback (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , user_id text
    , opportunity_id text
    , exposure_id text
    , reason jsonb DEFAULT '{}'::jsonb
    , comment text
    , created_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);

-- CareerOutcomeEvent
CREATE TABLE IF NOT EXISTS app.career_outcome_events (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , user_id text
    , opportunity_id text
    , application_id text
    , exposure_id text
    , stage jsonb DEFAULT '{}'::jsonb
    , occurred_at timestamptz
    , user_confirmed boolean
    , metadata jsonb DEFAULT '{}'::jsonb
    , created_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS career_outcome_events_user_id_occurred_at_idx ON app.career_outcome_events (user_id ASC, occurred_at DESC);

-- UserJourney
CREATE TABLE IF NOT EXISTS app.user_journeys (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , user_id text
    , session_id text
    , started_at timestamptz
    , ended_at timestamptz
    , event_count bigint
    , opportunity_ids jsonb DEFAULT '{}'::jsonb
    , search_queries text[] DEFAULT '{}'
    , path jsonb DEFAULT '{}'::jsonb
    , pogo_sticking_count bigint
    , reward_sum double precision
    , cold_start boolean
    , updated_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS user_journeys_user_id_ended_at_idx ON app.user_journeys (user_id ASC, ended_at DESC);
CREATE INDEX IF NOT EXISTS user_journeys_user_id_session_id_idx ON app.user_journeys (user_id ASC, session_id ASC);

-- ApplicationOutcome
CREATE TABLE IF NOT EXISTS app.application_outcomes (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , user_id text
    , opportunity_id text
    , application_id text
    , interaction_id text
    , prompt_type jsonb DEFAULT '{}'::jsonb
    , response jsonb DEFAULT '{}'::jsonb
    , metadata jsonb DEFAULT '{}'::jsonb
    , created_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS application_outcomes_user_id_opportunity_id_prompt_type_idx ON app.application_outcomes (user_id ASC, opportunity_id ASC, prompt_type ASC);

-- Application
CREATE TABLE IF NOT EXISTS app.applications (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , user_id text
    , opportunity_id text
    , status text
    , pipeline_state text
    , pipeline_notes text
    , pipeline_updated_at timestamptz
    , pipeline_updated_by text
    , resume_snapshot text
    , automation_mode text
    , automation_log text
    , submitted_at timestamptz
    , created_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);

-- OTPCode
CREATE TABLE IF NOT EXISTS app.otp_codes (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , email text
    , purpose text
    , otp_hash text
    , expires_at timestamptz
    , created_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS otp_codes_email_purpose_idx ON app.otp_codes (email ASC, purpose ASC);
CREATE INDEX IF NOT EXISTS otp_codes_expires_at_idx ON app.otp_codes (expires_at ASC);

-- KnowledgeChunk
CREATE TABLE IF NOT EXISTS app.knowledge_chunks (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , source_type jsonb DEFAULT '{}'::jsonb
    , source_id jsonb DEFAULT '{}'::jsonb
    , source_url text
    , title text
    , domain text
    , chunk_text text
    , embedding double precision[] DEFAULT '{}'
    , embedding_model text
    , chunk_index bigint
    , created_at timestamptz
    , updated_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS knowledge_chunks_source_type_source_id_chunk_index_idx ON app.knowledge_chunks (source_type ASC, source_id ASC, chunk_index ASC);

-- EvaluationRun
CREATE TABLE IF NOT EXISTS app.evaluation_runs (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , evaluator text
    , dataset_size bigint
    , top_k bigint
    , metrics jsonb DEFAULT '{}'::jsonb
    , details jsonb DEFAULT '{}'::jsonb
    , created_by_user_id text
    , created_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);

-- ImpactEvent
CREATE TABLE IF NOT EXISTS app.impact_events (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , user_id text
    , opportunity_id text
    , event_type jsonb DEFAULT '{}'::jsonb
    , metadata jsonb DEFAULT '{}'::jsonb
    , created_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);

-- Experiment
CREATE TABLE IF NOT EXISTS app.experiments (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , key jsonb DEFAULT '{}'::jsonb
    , name text
    , description text
    , status jsonb DEFAULT '{}'::jsonb
    , variants jsonb DEFAULT '{}'::jsonb
    , start_date timestamptz
    , end_date timestamptz
    , min_sample_size bigint
    , primary_metric jsonb DEFAULT '{}'::jsonb
    , guardrail_metrics text[] DEFAULT '{}'
    , default_variant text
    , winning_variant text
    , graduated_at timestamptz
    , graduation_history jsonb DEFAULT '{}'::jsonb
    , salt text
    , created_at timestamptz
    , updated_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);

-- ExperimentAssignment
CREATE TABLE IF NOT EXISTS app.experiment_assignments (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , user_id text
    , experiment_key text
    , variant text
    , bucket bigint
    , bucket_percent bigint
    , assigned_via_exclusion boolean
    , exclusion_reason text
    , assigned_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS experiment_assignments_user_id_experiment_key_idx ON app.experiment_assignments (user_id ASC, experiment_key ASC);

-- RankingModelVersion
CREATE TABLE IF NOT EXISTS app.ranking_model_versions (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , name text
    , is_active boolean
    , weights jsonb DEFAULT '{}'::jsonb
    , metrics jsonb DEFAULT '{}'::jsonb
    , trained_window_start timestamptz
    , trained_window_end timestamptz
    , training_rows bigint
    , label_window_hours bigint
    , split_strategy text
    , artifact_uri text
    , artifact_provider text
    , artifact_checksum_sha256 text
    , feature_schema jsonb DEFAULT '{}'::jsonb
    , serving_ready boolean
    , artifact_manifest jsonb DEFAULT '{}'::jsonb
    , baselines jsonb DEFAULT '{}'::jsonb
    , lifecycle jsonb DEFAULT '{}'::jsonb
    , training_metadata jsonb DEFAULT '{}'::jsonb
    , model_card jsonb DEFAULT '{}'::jsonb
    , notes text
    , created_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);

-- NLPModelVersion
CREATE TABLE IF NOT EXISTS app.nlp_model_versions (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , name text
    , is_active boolean
    , intent_labels text[] DEFAULT '{}'
    , intent_centroids jsonb DEFAULT '{}'::jsonb
    , intent_classifier_head jsonb DEFAULT '{}'::jsonb
    , entity_lexicon jsonb DEFAULT '{}'::jsonb
    , metrics jsonb DEFAULT '{}'::jsonb
    , confusion_matrix jsonb DEFAULT '{}'::jsonb
    , baseline_confusion_matrix jsonb DEFAULT '{}'::jsonb
    , evaluation_snapshot jsonb DEFAULT '{}'::jsonb
    , training_rows bigint
    , split_summary jsonb DEFAULT '{}'::jsonb
    , metadata jsonb DEFAULT '{}'::jsonb
    , notes text
    , created_at timestamptz
    , updated_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);

-- ModelDriftReport
CREATE TABLE IF NOT EXISTS app.model_drift_reports (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , model_version_id text
    , window_start timestamptz
    , window_end timestamptz
    , metrics jsonb DEFAULT '{}'::jsonb
    , alert boolean
    , alert_notified_at timestamptz
    , created_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);

-- RankingRequestTelemetry
CREATE TABLE IF NOT EXISTS app.ranking_request_telemetry (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , user_id text
    , request_kind jsonb DEFAULT '{}'::jsonb
    , requested_ranking_mode text
    , ranking_mode text
    , experiment_key text
    , experiment_variant text
    , rollout_variant text
    , rollout_bucket bigint
    , rollout_percent bigint
    , shadow_mode text
    , shadow_model_version_id text
    , shadow_candidate_count bigint
    , rag_template_label text
    , rag_template_version_id text
    , model_version_id text
    , surface text
    , success boolean
    , latency_ms double precision
    , results_count bigint
    , freshness_seconds double precision
    , error_code text
    , traffic_type jsonb DEFAULT '{}'::jsonb
    , created_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS ranking_request_telemetry_traffic_type_created_at_idx ON app.ranking_request_telemetry (traffic_type ASC, created_at DESC);
CREATE INDEX IF NOT EXISTS ranking_request_telemetry_request_kind_traffic_type_created_ ON app.ranking_request_telemetry (request_kind ASC, traffic_type ASC, created_at DESC);
CREATE INDEX IF NOT EXISTS ranking_request_telemetry_experiment_key_experiment_variant_ ON app.ranking_request_telemetry (experiment_key ASC, experiment_variant ASC, traffic_type ASC, created_at DESC);
CREATE INDEX IF NOT EXISTS ranking_request_telemetry_ranking_mode_traffic_type_created_ ON app.ranking_request_telemetry (ranking_mode ASC, traffic_type ASC, created_at DESC);
CREATE INDEX IF NOT EXISTS ranking_request_telemetry_success_created_at_idx ON app.ranking_request_telemetry (success ASC, created_at DESC);

-- RAGFeedbackEvent
CREATE TABLE IF NOT EXISTS app.rag_feedback_events (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , user_id text
    , request_id text
    , query text
    , feedback jsonb DEFAULT '{}'::jsonb
    , rag_template_label text
    , rag_template_version_id text
    , response_summary text
    , citations jsonb DEFAULT '{}'::jsonb
    , surface text
    , metadata jsonb DEFAULT '{}'::jsonb
    , created_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);

-- AskAIQuerySnapshot
CREATE TABLE IF NOT EXISTS app.ask_ai_query_snapshots (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , user_id text
    , request_id text
    , surface text
    , query text
    , schema_version bigint
    , response_summary text
    , deadline_urgency text
    , recommended_action text
    , citation_count bigint
    , top_opportunities jsonb DEFAULT '{}'::jsonb
    , metadata jsonb DEFAULT '{}'::jsonb
    , created_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS ask_ai_query_snapshots_user_id_request_id_idx ON app.ask_ai_query_snapshots (user_id ASC, request_id ASC);
CREATE INDEX IF NOT EXISTS ask_ai_query_snapshots_user_id_surface_created_at_idx ON app.ask_ai_query_snapshots (user_id ASC, surface ASC, created_at DESC);

-- AskAISavedQuery
CREATE TABLE IF NOT EXISTS app.ask_ai_saved_queries (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , user_id text
    , surface text
    , query text
    , created_at timestamptz
    , last_used_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS ask_ai_saved_queries_user_id_surface_query_idx ON app.ask_ai_saved_queries (user_id ASC, surface ASC, query ASC);
CREATE INDEX IF NOT EXISTS ask_ai_saved_queries_user_id_surface_last_used_at_idx ON app.ask_ai_saved_queries (user_id ASC, surface ASC, last_used_at DESC);

-- RAGTemplateVersion
CREATE TABLE IF NOT EXISTS app.rag_template_versions (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , template_key text
    , label jsonb DEFAULT '{}'::jsonb
    , version bigint
    , description text
    , status jsonb DEFAULT '{}'::jsonb
    , is_active boolean
    , is_online_candidate boolean
    , retrieval_top_k bigint
    , retrieval_settings jsonb DEFAULT '{}'::jsonb
    , system_prompt text
    , judge_rubric text
    , acceptance_thresholds jsonb DEFAULT '{}'::jsonb
    , metadata jsonb DEFAULT '{}'::jsonb
    , created_at timestamptz
    , updated_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS rag_template_versions_template_key_version_idx ON app.rag_template_versions (template_key ASC, version ASC);

-- RAGTemplateEvaluationRun
CREATE TABLE IF NOT EXISTS app.rag_template_evaluation_runs (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , template_key text
    , template_label text
    , template_version_id text
    , mode jsonb DEFAULT '{}'::jsonb
    , metrics jsonb DEFAULT '{}'::jsonb
    , thresholds jsonb DEFAULT '{}'::jsonb
    , accepted boolean
    , notes text
    , created_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);

-- VectorIndexEntry
CREATE TABLE IF NOT EXISTS app.vector_index_entries (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , opportunity_id text
    , text_hash text
    , text text
    , embedding double precision[] DEFAULT '{}'
    , metadata jsonb DEFAULT '{}'::jsonb
    , updated_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);

-- BackgroundJob
CREATE TABLE IF NOT EXISTS app.background_jobs (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , job_type text
    , payload jsonb DEFAULT '{}'::jsonb
    , status text
    , attempts bigint
    , max_attempts bigint
    , run_after timestamptz
    , locked_by text
    , locked_at timestamptz
    , started_at timestamptz
    , finished_at timestamptz
    , last_error text
    , last_error_at timestamptz
    , result jsonb DEFAULT '{}'::jsonb
    , dedupe_key text
    , created_at timestamptz
    , updated_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS background_jobs_status_run_after_created_at_idx ON app.background_jobs (status ASC, run_after ASC, created_at ASC);
CREATE INDEX IF NOT EXISTS background_jobs_dedupe_key_status_idx ON app.background_jobs (dedupe_key ASC, status ASC);
CREATE INDEX IF NOT EXISTS background_jobs_locked_by_locked_at_idx ON app.background_jobs (locked_by ASC, locked_at ASC);

-- RecruiterAuditLog
CREATE TABLE IF NOT EXISTS app.recruiter_audit_logs (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , recruiter_user_id text
    , action text
    , entity_type text
    , entity_id text
    , opportunity_id text
    , application_id text
    , metadata jsonb DEFAULT '{}'::jsonb
    , created_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);

-- AuthAuditEvent
CREATE TABLE IF NOT EXISTS app.auth_audit_events (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , event_type text
    , email text
    , account_type text
    , purpose text
    , success boolean
    , reason text
    , ip_address text
    , user_agent text
    , user_id text
    , lock_applied boolean
    , lock_until timestamptz
    , created_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS auth_audit_events_created_at_idx ON app.auth_audit_events (created_at ASC);

-- AuthAbuseState
CREATE TABLE IF NOT EXISTS app.auth_abuse_states (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , key text
    , email text
    , action text
    , purpose text
    , failed_attempts bigint
    , first_failed_at timestamptz
    , last_failed_at timestamptz
    , lock_until timestamptz
    , updated_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS auth_abuse_states_key_idx ON app.auth_abuse_states (key ASC);

-- AnalyticsDailyAggregate
CREATE TABLE IF NOT EXISTS app.analytics_daily_aggregates (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , date text
    , metric_type text
    , traffic_type text
    , ranking_mode text
    , experiment_key text
    , experiment_variant text
    , request_kind text
    , metrics jsonb DEFAULT '{}'::jsonb
    , created_at timestamptz
    , updated_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS analytics_daily_aggregates_date_metric_type_traffic_type_ran ON app.analytics_daily_aggregates (date ASC, metric_type ASC, traffic_type ASC, ranking_mode ASC, experiment_key ASC, experiment_variant ASC, request_kind ASC);

-- AnalyticsFunnelAggregate
CREATE TABLE IF NOT EXISTS app.analytics_funnel_aggregates (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , date text
    , traffic_type text
    , ranking_mode text
    , experiment_key text
    , experiment_variant text
    , stage_counts jsonb DEFAULT '{}'::jsonb
    , rates jsonb DEFAULT '{}'::jsonb
    , metadata jsonb DEFAULT '{}'::jsonb
    , created_at timestamptz
    , updated_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS analytics_funnel_aggregates_date_traffic_type_ranking_mode_e ON app.analytics_funnel_aggregates (date ASC, traffic_type ASC, ranking_mode ASC, experiment_key ASC, experiment_variant ASC);

-- AnalyticsCohortAggregate
CREATE TABLE IF NOT EXISTS app.analytics_cohort_aggregates (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , cohort_date text
    , days_since_cohort bigint
    , traffic_type text
    , users_in_cohort bigint
    , active_users bigint
    , applying_users bigint
    , retention_rate double precision
    , apply_rate double precision
    , created_at timestamptz
    , updated_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS analytics_cohort_aggregates_cohort_date_days_since_cohort_tr ON app.analytics_cohort_aggregates (cohort_date ASC, days_since_cohort ASC, traffic_type ASC);

-- FeatureStoreRow
CREATE TABLE IF NOT EXISTS app.feature_store_rows (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , row_key text
    , date text
    , user_id text
    , opportunity_id text
    , ranking_mode text
    , experiment_key text
    , experiment_variant text
    , traffic_type text
    , rank_position bigint
    , match_score double precision
    , features jsonb DEFAULT '{}'::jsonb
    , labels jsonb DEFAULT '{}'::jsonb
    , source_event_id text
    , created_at timestamptz
    , updated_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS feature_store_rows_row_key_idx ON app.feature_store_rows (row_key ASC);
CREATE INDEX IF NOT EXISTS feature_store_rows_traffic_type_updated_at_idx ON app.feature_store_rows (traffic_type ASC, updated_at DESC);
CREATE INDEX IF NOT EXISTS feature_store_rows_user_id_opportunity_id_updated_at_idx ON app.feature_store_rows (user_id ASC, opportunity_id ASC, updated_at DESC);
CREATE INDEX IF NOT EXISTS feature_store_rows_experiment_key_experiment_variant_traffic ON app.feature_store_rows (experiment_key ASC, experiment_variant ASC, traffic_type ASC, updated_at DESC);

-- MlopsIncident
CREATE TABLE IF NOT EXISTS app.mlops_incidents (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , incident_key text
    , source_type text
    , source_id text
    , report_id text
    , model_version_id text
    , severity text
    , status text
    , title text
    , summary text
    , owner text
    , root_cause text
    , mitigation text
    , lessons_learned text
    , review_due_at timestamptz
    , breached_sla boolean
    , resolved_at timestamptz
    , timeline jsonb DEFAULT '{}'::jsonb
    , action_items jsonb DEFAULT '{}'::jsonb
    , metadata jsonb DEFAULT '{}'::jsonb
    , created_at timestamptz
    , updated_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS mlops_incidents_incident_key_idx ON app.mlops_incidents (incident_key ASC);

-- AssistantConversationTurn
CREATE TABLE IF NOT EXISTS app.assistant_conversation_turns (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , user_id text
    , surface text
    , role text
    , content text
    , metadata jsonb DEFAULT '{}'::jsonb
    , request_id text
    , created_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS assistant_conversation_turns_user_id_surface_created_at_idx ON app.assistant_conversation_turns (user_id ASC, surface ASC, created_at DESC);

-- AssistantMemoryState
CREATE TABLE IF NOT EXISTS app.assistant_memory_states (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , user_id text
    , surface text
    , summary text
    , summarized_turns bigint
    , updated_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);

-- AssistantAuditEvent
CREATE TABLE IF NOT EXISTS app.assistant_audit_events (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , user_id text
    , surface text
    , request_id text
    , route text
    , tool_name text
    , prompt_version text
    , latency_ms double precision
    , success boolean
    , citation_count bigint
    , summary_used boolean
    , metadata jsonb DEFAULT '{}'::jsonb
    , created_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);

-- ModelArtifactVersion
CREATE TABLE IF NOT EXISTS app.model_artifact_versions (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , model_family text
    , model_version_id text
    , artifact_uri text
    , storage_provider text
    , checksum_sha256 text
    , local_cache_path text
    , feature_schema jsonb DEFAULT '{}'::jsonb
    , training_metadata jsonb DEFAULT '{}'::jsonb
    , metadata jsonb DEFAULT '{}'::jsonb
    , status text
    , verified boolean
    , reviewer text
    , review_notes text
    , reviewed_at timestamptz
    , promoted_at timestamptz
    , created_at timestamptz
    , updated_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);

-- WarehouseExportRun
CREATE TABLE IF NOT EXISTS app.warehouse_export_runs (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , traffic_type text
    , export_format text
    , lookback_days bigint
    , status text
    , exported_tables text[] DEFAULT '{}'
    , raw_files jsonb DEFAULT '{}'::jsonb
    , mart_files jsonb DEFAULT '{}'::jsonb
    , metadata jsonb DEFAULT '{}'::jsonb
    , error text
    , created_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);

-- SecurityEvent
CREATE TABLE IF NOT EXISTS app.security_events (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , event_type text
    , source text
    , metadata jsonb DEFAULT '{}'::jsonb
    , created_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);

-- DuplicateMergeEvent
CREATE TABLE IF NOT EXISTS app.duplicate_merge_events (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , canonical_opportunity_id text
    , duplicate_opportunity_id text
    , canonical_source text
    , duplicate_source text
    , canonical_source_id text
    , duplicate_source_id text
    , canonical_url text
    , duplicate_url text
    , stage text
    , score double precision
    , created_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS duplicate_merge_events_canonical_source_duplicate_source_cre ON app.duplicate_merge_events (canonical_source ASC, duplicate_source ASC, created_at DESC);
CREATE INDEX IF NOT EXISTS duplicate_merge_events_canonical_opportunity_id_created_at_i ON app.duplicate_merge_events (canonical_opportunity_id ASC, created_at DESC);

-- ScraperRunLog
CREATE TABLE IF NOT EXISTS app.scraper_run_logs (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , source_name text
    , run_start timestamptz
    , run_end timestamptz
    , status jsonb DEFAULT '{}'::jsonb
    , items_fetched bigint
    , items_parsed bigint
    , items_inserted bigint
    , items_updated bigint
    , items_deduplicated bigint
    , items_out_of_scope bigint
    , items_non_posting bigint
    , parse_error_count bigint
    , error_samples jsonb DEFAULT '{}'::jsonb
    , p50_parse_time_ms double precision
    , p95_parse_time_ms double precision
    , avg_trust_score double precision
    , silent_failure boolean
    , created_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS scraper_run_logs_source_name_run_end_idx ON app.scraper_run_logs (source_name ASC, run_end DESC);
CREATE INDEX IF NOT EXISTS scraper_run_logs_source_name_status_run_end_idx ON app.scraper_run_logs (source_name ASC, status ASC, run_end DESC);

-- DiscoveredSource
CREATE TABLE IF NOT EXISTS app.discovered_sources (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , url text
    , domain text
    , name text
    , source_type text
    , priority_score double precision
    , priority_reasons text[] DEFAULT '{}'
    , priority_features jsonb DEFAULT '{}'::jsonb
    , discovery_method jsonb DEFAULT '{}'::jsonb
    , discovery_query text
    , discovered_at timestamptz
    , discovered_by text
    , status jsonb DEFAULT '{}'::jsonb
    , qualification_score double precision
    , qualification_details jsonb DEFAULT '{}'::jsonb
    , qualified_at timestamptz
    , extraction_confidence double precision
    , parser_template jsonb DEFAULT '{}'::jsonb
    , sample_opportunities jsonb DEFAULT '{}'::jsonb
    , extraction_model_version text
    , extracted_at timestamptz
    , trust_score double precision
    , trust_breakdown jsonb DEFAULT '{}'::jsonb
    , trust_score_boost double precision
    , probation_start timestamptz
    , probation_runs bigint
    , probation_items_fetched integer[] DEFAULT '{}'
    , probation_items_passed_quality integer[] DEFAULT '{}'
    , probation_parse_rates double precision[] DEFAULT '{}'
    , probation_failures text[] DEFAULT '{}'
    , promoted_at timestamptz
    , promoted_by text
    , scraper_key text
    , total_opportunities_contributed bigint
    , rejection_reason text
    , rejected_at timestamptz
    , retry_after timestamptz
    , admin_notes text
    , requires_admin_review boolean
    , admin_hold boolean
    , admin_reviewed_by text
    , admin_reviewed_at timestamptz
    , consecutive_failures bigint
    , health_score double precision
    , last_scraped_at timestamptz
    , last_health_reason text
    , updated_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS discovered_sources_domain_idx ON app.discovered_sources (domain ASC);
CREATE INDEX IF NOT EXISTS discovered_sources_status_idx ON app.discovered_sources (status ASC);
CREATE INDEX IF NOT EXISTS discovered_sources_trust_score_idx ON app.discovered_sources (trust_score DESC);
CREATE INDEX IF NOT EXISTS discovered_sources_discovered_at_idx ON app.discovered_sources (discovered_at DESC);
CREATE INDEX IF NOT EXISTS discovered_sources_status_priority_score_discovered_at_idx ON app.discovered_sources (status ASC, priority_score DESC, discovered_at ASC);
CREATE INDEX IF NOT EXISTS discovered_sources_source_type_status_idx ON app.discovered_sources (source_type ASC, status ASC);
CREATE INDEX IF NOT EXISTS discovered_sources_discovered_by_discovered_at_idx ON app.discovered_sources (discovered_by ASC, discovered_at DESC);

-- CompanySeed
CREATE TABLE IF NOT EXISTS app.company_seeds (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , company_name text
    , domain text
    , careers_url text
    , industry text
    , company_size text
    , india_presence boolean
    , student_friendly boolean
    , priority_tier text
    , source_category text
    , check_cadence_hours bigint
    , target_roles text[] DEFAULT '{}'
    , notes text
    , added_by text
    , discovered_source_id text
    , last_checked_at timestamptz
    , created_at timestamptz
    , updated_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS company_seeds_domain_idx ON app.company_seeds (domain ASC);
CREATE INDEX IF NOT EXISTS company_seeds_india_presence_student_friendly_idx ON app.company_seeds (india_presence ASC, student_friendly ASC);
CREATE INDEX IF NOT EXISTS company_seeds_priority_tier_last_checked_at_idx ON app.company_seeds (priority_tier ASC, last_checked_at ASC);
CREATE INDEX IF NOT EXISTS company_seeds_source_category_idx ON app.company_seeds (source_category ASC);
CREATE INDEX IF NOT EXISTS company_seeds_discovered_source_id_idx ON app.company_seeds (discovered_source_id ASC);

-- SourceDiscoveryRun
CREATE TABLE IF NOT EXISTS app.source_discovery_runs (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , run_id text
    , triggered_by text
    , started_at timestamptz
    , finished_at timestamptz
    , status text
    , queries_executed bigint
    , urls_discovered bigint
    , urls_already_known bigint
    , urls_queued_for_qualification bigint
    , qualified bigint
    , failed_qualification bigint
    , extracted bigint
    , failed_extraction bigint
    , promoted bigint
    , rejected bigint
    , errors text[] DEFAULT '{}'
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS source_discovery_runs_run_id_idx ON app.source_discovery_runs (run_id ASC);
CREATE INDEX IF NOT EXISTS source_discovery_runs_started_at_idx ON app.source_discovery_runs (started_at DESC);
CREATE INDEX IF NOT EXISTS source_discovery_runs_status_idx ON app.source_discovery_runs (status ASC);

-- BadDomainEntry
CREATE TABLE IF NOT EXISTS app.bad_domain_list (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , domain text
    , reason text
    , added_at timestamptz
    , added_by text
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS bad_domain_list_domain_idx ON app.bad_domain_list (domain ASC);

-- ProbationOpportunity
CREATE TABLE IF NOT EXISTS app.probation_opportunities (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , discovered_source_id text
    , scraper_key text
    , title text
    , company text
    , url text
    , raw_payload jsonb DEFAULT '{}'::jsonb
    , quality_score double precision
    , run_number bigint
    , created_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS probation_opportunities_discovered_source_id_run_number_idx ON app.probation_opportunities (discovered_source_id ASC, run_number ASC);
CREATE INDEX IF NOT EXISTS probation_opportunities_url_idx ON app.probation_opportunities (url ASC);

-- ScraperRegistration
CREATE TABLE IF NOT EXISTS app.scraper_registrations (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , scraper_key text
    , source_name text
    , domain text
    , careers_url text
    , source_type text
    , extraction_method text
    , parser_template jsonb DEFAULT '{}'::jsonb
    , trust_score double precision
    , status jsonb DEFAULT '{}'::jsonb
    , schedule text
    , last_scraped_at timestamptz
    , health_score double precision
    , total_yield bigint
    , consecutive_failures bigint
    , stale_template_failures bigint
    , discovered_source_id text
    , is_original_source boolean
    , created_at timestamptz
    , updated_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS scraper_registrations_scraper_key_idx ON app.scraper_registrations (scraper_key ASC);
CREATE INDEX IF NOT EXISTS scraper_registrations_domain_idx ON app.scraper_registrations (domain ASC);
CREATE INDEX IF NOT EXISTS scraper_registrations_status_idx ON app.scraper_registrations (status ASC);
CREATE INDEX IF NOT EXISTS scraper_registrations_discovered_source_id_idx ON app.scraper_registrations (discovered_source_id ASC);

-- DiscoveryLLMCall
CREATE TABLE IF NOT EXISTS app.discovery_llm_calls (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , domain text
    , method text
    , model text
    , tokens_used bigint
    , confidence double precision
    , cost_estimate_usd double precision
    , success boolean
    , error text
    , created_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS discovery_llm_calls_domain_created_at_idx ON app.discovery_llm_calls (domain ASC, created_at DESC);
CREATE INDEX IF NOT EXISTS discovery_llm_calls_created_at_idx ON app.discovery_llm_calls (created_at DESC);

-- EmployerCareersClaim
CREATE TABLE IF NOT EXISTS app.employer_careers_claims (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid()
    , legacy_mongo_id text UNIQUE
    , employer_user_id text
    , company_name text
    , company_domain text
    , careers_url text
    , verification_token text
    , verification_status text
    , discovered_source_id text
    , created_at timestamptz
    , verified_at timestamptz
    , extras jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS employer_careers_claims_employer_user_id_created_at_idx ON app.employer_careers_claims (employer_user_id ASC, created_at DESC);
CREATE INDEX IF NOT EXISTS employer_careers_claims_verification_token_idx ON app.employer_careers_claims (verification_token ASC);
CREATE INDEX IF NOT EXISTS employer_careers_claims_company_domain_idx ON app.employer_careers_claims (company_domain ASC);
