"""Employer job boards, each verified to return live postings.

Generated, not hand-written. Every entry here was resolved by probing the
employer's own careers page, identifying the applicant tracking system behind
it, and then calling that platform's API and requiring at least one real posting
back. Companies whose boards answered with nothing are absent by design: a
source that yields no rows is configuration to maintain forever for no listings.

`verified_jobs` is the count observed when the board was last probed. It is a
record of what the board returned that day, not a live figure, and exists so a
board that silently empties out can be spotted against its own history.

Workday tokens are "tenant|host|site" because all three parts are needed to
build the endpoint and none can be derived from the others.

To refresh: re-run the discovery probe and regenerate this file.
"""

from __future__ import annotations

from typing import NamedTuple


class CompanyBoard(NamedTuple):
    company: str
    platform: str
    token: str
    verified_jobs: int


COMPANY_BOARDS: tuple[CompanyBoard, ...] = (
    CompanyBoard('Bosch', 'smartrecruiters', 'BoschGroup', 4719),
    CompanyBoard('Micron', 'workday', 'micron|wd1|External', 2718),
    CompanyBoard('Johnson Controls', 'workday', 'jci|wd5|JCI', 2670),
    CompanyBoard('Anduril Industries', 'greenhouse', 'andurilindustries', 2171),
    CompanyBoard('Accenture', 'workday', 'accenture|wd103|AccentureCareers', 2000),
    CompanyBoard('Airbus', 'workday', 'ag|wd3|Airbus', 2000),
    CompanyBoard('Genpact', 'workday', 'genpact|wd108|External_Careers', 2000),
    CompanyBoard('NVIDIA', 'workday', 'nvidia|wd5|NVIDIAExternalCareerSite', 2000),
    CompanyBoard('Target', 'workday', 'target|wd5|targetcareers', 2000),
    CompanyBoard('Sopra Steria', 'smartrecruiters', 'SopraSteria1', 1963),
    CompanyBoard('IQVIA', 'workday', 'iqvia|wd1|IQVIA', 1952),
    CompanyBoard('Applied Materials', 'workday', 'amat|wd1|External', 1839),
    CompanyBoard('Capital One', 'workday', 'capitalone|wd12|Capital_One', 1757),
    CompanyBoard('Trane Technologies', 'workday', 'tranetechnologies|wd12|Trane_Technologies_Careers', 1431),
    CompanyBoard('Palo Alto Networks', 'workday', 'paloaltonetworks|wd5|panwexternalcareers', 1384),
    CompanyBoard('Roche', 'workday', 'roche|wd3|roche-ext', 1191),
    CompanyBoard('Valeo', 'workday', 'valeo|wd3|valeo_jobs', 1159),
    CompanyBoard('Medtronic', 'workday', 'medtronic|wd1|medtroniccareers', 1138),
    CompanyBoard('Stryker', 'workday', 'stryker|wd1|StrykerCareers', 1128),
    CompanyBoard('Mastercard', 'workday', 'mastercard|wd1|CorporateCareers', 1113),
    CompanyBoard('Cisco', 'workday', 'cisco|wd5|cisco_careers', 1065),
    CompanyBoard('Splunk', 'workday', 'cisco|wd5|Cisco_Careers', 1064),
    CompanyBoard('Juniper', 'workday', 'hpe|wd5|Jobsathpe', 1061),
    CompanyBoard('Barclays', 'workday', 'barclays|wd3|External_Career_Site_Barclays', 1038),
    CompanyBoard('Novartis', 'workday', 'novartis|wd3|novartis_careers', 999),
    CompanyBoard('Analog Devices', 'workday', 'analogdevices|wd1|External', 967),
    CompanyBoard('GE Healthcare', 'workday', 'gehc|wd5|GEHC_ExternalSite', 961),
    CompanyBoard('Philips', 'workday', 'philips|wd3|jobs-and-careers', 953),
    CompanyBoard('Continental', 'smartrecruiters', 'continental', 931),
    CompanyBoard('Adobe', 'workday', 'adobe|wd5|external_experienced', 808),
    CompanyBoard('Databricks', 'greenhouse', 'databricks', 808),
    CompanyBoard('NXP', 'workday', 'nxp|wd3|Careers', 806),
    CompanyBoard('RELX India', 'workday', 'relx|wd3|relx', 766),
    CompanyBoard('Aptiv', 'workday', 'aptiv|wd5|aptiv_careers', 736),
    CompanyBoard('OpenAI', 'ashby', 'openai', 735),
    CompanyBoard('HP', 'workday', 'hp|wd5|ExternalCareerSite', 718),
    CompanyBoard('Boeing', 'workday', 'boeing|wd1|External_Careers', 713),
    CompanyBoard('GSK', 'workday', 'gsk|wd5|GSKCareers', 688),
    CompanyBoard('Intel', 'workday', 'intel|wd1|External', 681),
    CompanyBoard('Airwallex', 'ashby', 'airwallex', 628),
    CompanyBoard('Samsung Networks', 'workday', 'sec|wd3|Samsung_Careers', 614),
    CompanyBoard('Cadence', 'workday', 'cadence|wd1|External_Careers', 581),
    CompanyBoard('Baxter', 'workday', 'baxter|wd1|baxter', 558),
    CompanyBoard('Stripe', 'greenhouse', 'stripe', 550),
    CompanyBoard('Accor', 'smartrecruiters', 'accor', 531),
    CompanyBoard('Becton Dickinson', 'workday', 'bdx|wd1|EXTERNAL_CAREER_SITE_USA', 509),
    CompanyBoard('Netflix', 'custom', 'netflix', 483),
    CompanyBoard('Autodesk', 'workday', 'autodesk|wd1|Ext', 482),
    CompanyBoard('Expeditors', 'smartrecruiters', 'expeditors', 471),
    CompanyBoard('ServiceNow', 'smartrecruiters', 'servicenow', 460),
    CompanyBoard('Fiserv', 'workday', 'fiserv|wd5|EXT', 452),
    CompanyBoard('Shield AI', 'lever', 'shieldai', 441),
    CompanyBoard('Warner Bros. Discovery', 'workday', 'warnerbros|wd5|global', 441),
    CompanyBoard('NielsenIQ', 'smartrecruiters', 'nielseniq', 437),
    CompanyBoard('Datadog', 'greenhouse', 'datadog', 433),
    CompanyBoard('Rockwell Automation', 'workday', 'rockwellautomation|wd1|External_Rockwell_Automation', 433),
    CompanyBoard('eBay', 'workday', 'ebay|wd5|apply', 433),
    CompanyBoard('Thomson Reuters', 'workday', 'thomsonreuters|wd5|External_Career_Site', 430),
    CompanyBoard('CrowdStrike', 'workday', 'crowdstrike|wd5|crowdstrikecareers', 423),
    CompanyBoard('Wise', 'smartrecruiters', 'wise', 406),
    CompanyBoard('MongoDB', 'greenhouse', 'mongodb', 405),
    CompanyBoard('Anthropic', 'greenhouse', 'anthropic', 398),
    CompanyBoard('Snowflake', 'ashby', 'snowflake', 394),
    CompanyBoard('BP', 'workday', 'bpinternational|wd3|bpCareers', 377),
    CompanyBoard('Western Digital', 'smartrecruiters', 'westerndigital', 361),
    CompanyBoard('Harvey', 'ashby', 'harvey', 358),
    CompanyBoard('Okta', 'greenhouse', 'okta', 343),
    CompanyBoard('Workday', 'workday', 'workday|wd5|Workday', 338),
    CompanyBoard('Lucid', 'greenhouse', 'lucidmotors', 323),
    CompanyBoard('NICE', 'greenhouse', 'nice', 308),
    CompanyBoard('Canonical', 'greenhouse', 'canonical', 303),
    CompanyBoard('Zscaler', 'greenhouse', 'zscaler', 303),
    CompanyBoard('Brex', 'greenhouse', 'brex', 302),
    CompanyBoard('Pure Storage', 'greenhouse', 'purestorage', 301),
    CompanyBoard('CoreWeave', 'greenhouse', 'coreweave', 294),
    CompanyBoard('NetApp', 'eightfold', 'netapp.eightfold.ai', 294),
    CompanyBoard('Cloudflare', 'greenhouse', 'cloudflare', 290),
    CompanyBoard('S&P Global', 'workday', 'spgi|wd5|SPGI_Careers', 289),
    CompanyBoard('Agoda', 'greenhouse', 'agoda', 287),
    CompanyBoard('CAE', 'workday', 'cae|wd3|career', 283),
    CompanyBoard('Verkada', 'greenhouse', 'verkada', 276),
    CompanyBoard('IFS', 'smartrecruiters', 'IFS1', 269),
    CompanyBoard('Unilever', 'workday', 'unilever|wd3|Unilever_Experienced_Professionals', 261),
    CompanyBoard('Zipline', 'greenhouse', 'flyzipline', 259),
    CompanyBoard('Braze', 'greenhouse', 'braze', 251),
    CompanyBoard('Celonis', 'greenhouse', 'celonis', 251),
    CompanyBoard('Paytm', 'lever', 'paytm', 240),
    CompanyBoard('Arista Networks', 'smartrecruiters', 'aristanetworks', 237),
    CompanyBoard('Canva', 'smartrecruiters', 'canva', 237),
    CompanyBoard('Elastic', 'greenhouse', 'elastic', 232),
    CompanyBoard('Elastic Path', 'greenhouse', 'elastic', 232),
    CompanyBoard('AVEVA', 'workday', 'aveva|wd3|AVEVA_careers', 231),
    CompanyBoard('F5', 'workday', 'ffive|wd5|f5jobs', 229),
    CompanyBoard('NTT DATA', 'workday', 'nttglobaldatacenters|wd501|External', 229),
    CompanyBoard('NTT Ltd', 'workday', 'nttglobaldatacenters|wd501|External', 229),
    CompanyBoard('Pinterest', 'greenhouse', 'pinterest', 226),
    CompanyBoard('ElevenLabs', 'ashby', 'elevenlabs', 225),
    CompanyBoard('Jane Street', 'greenhouse', 'janestreet', 225),
    CompanyBoard('Scale AI', 'greenhouse', 'scaleai', 219),
    CompanyBoard('Fivetran', 'greenhouse', 'fivetran', 200),
    CompanyBoard('Cohesity', 'workday', 'cohesity|wd5|cohesity_careers', 194),
    CompanyBoard('Appian', 'greenhouse', 'appian', 192),
    CompanyBoard('Genesys', 'workday', 'genesys|wd1|Genesys', 192),
    CompanyBoard('Airbnb', 'greenhouse', 'airbnb', 189),
    CompanyBoard('Nasdaq', 'workday', 'nasdaq|wd1|Global_External_Site', 188),
    CompanyBoard('Blackstone', 'workday', 'blackstone|wd1|Blackstone_Careers', 187),
    CompanyBoard('Reddit', 'greenhouse', 'reddit', 187),
    CompanyBoard('Morningstar', 'workday', 'morningstar|wd5|morningstar', 186),
    CompanyBoard('GitLab', 'greenhouse', 'gitlab', 185),
    CompanyBoard('Checkout.com', 'ashby', 'checkout.com', 178),
    CompanyBoard('Figma', 'greenhouse', 'figma', 176),
    CompanyBoard('Clarivate', 'workday', 'clarivate|wd3|Clarivate_Careers', 175),
    CompanyBoard('Mistral AI', 'ashby', 'mistral.ai', 171),
    CompanyBoard('Anaplan', 'greenhouse', 'anaplan', 168),
    CompanyBoard('Riot Games', 'greenhouse', 'riotgames', 164),
    CompanyBoard('Coinbase', 'greenhouse', 'coinbase', 163),
    CompanyBoard('Workato', 'greenhouse', 'workato', 163),
    CompanyBoard('IMC', 'greenhouse', 'imc', 158),
    CompanyBoard('IMC Trading', 'greenhouse', 'imc', 158),
    CompanyBoard('Proofpoint', 'workday', 'proofpoint|wd5|proofpointcareers', 157),
    CompanyBoard('General Mills', 'workday', 'genmills|wd1|GMI_External_Careers', 156),
    CompanyBoard('Freshworks', 'smartrecruiters', 'freshworks', 154),
    CompanyBoard('Ciena', 'workday', 'ciena|wd5|Careers', 153),
    CompanyBoard('Flexport', 'greenhouse', 'flexport', 153),
    CompanyBoard('Asana', 'greenhouse', 'asana', 148),
    CompanyBoard('Epic Games', 'greenhouse', 'epicgames', 148),
    CompanyBoard('Red Hat', 'workday', 'redhat|wd5|jobs', 147),
    CompanyBoard('Netskope', 'greenhouse', 'netskope', 143),
    CompanyBoard('Cohere', 'ashby', 'cohere', 140),
    CompanyBoard('Grafana Labs', 'greenhouse', 'grafanalabs', 139),
    CompanyBoard('Illumina', 'workday', 'illumina|wd1|illumina-careers', 130),
    CompanyBoard('Tenstorrent', 'greenhouse', 'tenstorrent', 128),
    CompanyBoard('Cato Networks', 'greenhouse', 'catonetworks', 125),
    CompanyBoard('Intercom', 'greenhouse', 'intercom', 124),
    CompanyBoard('Cerebras Systems', 'ashby', 'cerebras', 122),
    CompanyBoard('Ramp', 'ashby', 'ramp', 120),
    CompanyBoard('Sonar', 'lever', 'sonarsource', 118),
    CompanyBoard('Arctic Wolf', 'workday', 'arcticwolf|wd1|External', 117),
    CompanyBoard('Skydio', 'ashby', 'skydio', 115),
    CompanyBoard('Notion', 'ashby', 'notion', 110),
    CompanyBoard('SiFive', 'workday', 'sifive|wd1|sifivecareers', 110),
    CompanyBoard('Plaid', 'ashby', 'plaid', 108),
    CompanyBoard('Sophos', 'lever', 'sophos', 108),
    CompanyBoard('Postman', 'greenhouse', 'postman', 107),
    CompanyBoard('Jump Trading', 'greenhouse', 'jumptrading', 106),
    CompanyBoard('Rubrik', 'greenhouse', 'rubrik', 106),
    CompanyBoard('Lattice Semiconductor', 'workday', 'latticesemi|wd5|latticesemiconductorscareers', 104),
    CompanyBoard('Protiviti', 'workday', 'roberthalf|wd1|ProtivitiNA', 104),
    CompanyBoard('Spotify', 'lever', 'spotify', 103),
    CompanyBoard('PayPal', 'workday', 'paypal|wd1|jobs', 102),
    CompanyBoard('Tide', 'greenhouse', 'tide', 102),
    CompanyBoard('WorldQuant', 'greenhouse', 'worldquant', 101),
    CompanyBoard('Smartsheet', 'greenhouse', 'smartsheet', 99),
    CompanyBoard('Harness', 'greenhouse', 'harnessinc', 96),
    CompanyBoard('Fidelity International', 'workday', 'fil|wd3|001', 95),
    CompanyBoard('Collins Aerospace', 'recruitee', 'collins', 94),
    CompanyBoard('TCS', 'greenhouse', 'tcs', 94),
    CompanyBoard('SolarWinds', 'greenhouse', 'solarwinds', 93),
    CompanyBoard('Extreme Networks', 'lever', 'extremenetworks', 92),
    CompanyBoard('JetBrains', 'greenhouse', 'jetbrains', 92),
    CompanyBoard('Kong', 'ashby', 'kong', 91),
    CompanyBoard('Grant Thornton', 'recruitee', 'grantthornton', 90),
    CompanyBoard('Cloudera', 'workday', 'cloudera|wd5|External_Career', 87),
    CompanyBoard('Perplexity', 'ashby', 'perplexity', 87),
    CompanyBoard('HighLevel', 'lever', 'gohighlevel', 85),
    CompanyBoard('Vercel', 'greenhouse', 'vercel', 80),
    CompanyBoard('Codeium', 'ashby', 'cognition', 79),
    CompanyBoard('Cognition AI', 'ashby', 'cognition', 79),
    CompanyBoard('Deepgram', 'ashby', 'Deepgram', 78),
    CompanyBoard('KnowBe4', 'greenhouse', 'knowbe4', 78),
    CompanyBoard('C3 AI', 'greenhouse', 'c3iot', 75),
    CompanyBoard('Darktrace', 'workday', 'darktrace|wd3|DarktaceExternal', 75),
    CompanyBoard('Krafton', 'greenhouse', 'krafton', 75),
    CompanyBoard('Rockstar Games', 'greenhouse', 'rockstargames', 74),
    CompanyBoard('Tower Research Capital', 'greenhouse', 'towerresearchcapital', 74),
    CompanyBoard('Abnormal AI', 'greenhouse', 'abnormalsecurity', 73),
    CompanyBoard('Commvault', 'greenhouse', 'commvault', 73),
    CompanyBoard('PhonePe', 'greenhouse', 'phonepe', 72),
    CompanyBoard('Abacus.AI', 'greenhouse', 'abacus', 70),
    CompanyBoard('Chainguard', 'greenhouse', 'chainguard', 70),
    CompanyBoard('Allegro MicroSystems', 'workday', 'allegromicro|wd5|AllegroCareers', 69),
    CompanyBoard('InMobi', 'greenhouse', 'inmobi', 69),
    CompanyBoard('Alteryx', 'workday', 'alteryx|wd108|AlteryxCareers', 68),
    CompanyBoard('Illumio', 'ashby', 'illumio', 66),
    CompanyBoard('Cribl', 'greenhouse', 'cribl', 65),
    CompanyBoard('Duolingo', 'greenhouse', 'duolingo', 65),
    CompanyBoard('1Password', 'ashby', '1password', 64),
    CompanyBoard('Baseten', 'ashby', 'baseten', 64),
    CompanyBoard('Deloitte', 'workday', 'deloitteie|wd3|Experienced_Professionals', 64),
    CompanyBoard('Twitch', 'greenhouse', 'twitch', 62),
    CompanyBoard('FactSet', 'workday', 'factset|wd108|FactSetCareers', 61),
    CompanyBoard('Thoughtworks', 'greenhouse', 'thoughtworks', 59),
    CompanyBoard('Together AI', 'greenhouse', 'togetherai', 59),
    CompanyBoard('Docker', 'ashby', 'docker', 58),
    CompanyBoard('Supabase', 'ashby', 'supabase', 58),
    CompanyBoard('Sarvam AI', 'ashby', 'sarvam', 57),
    CompanyBoard('Tailscale', 'greenhouse', 'tailscale', 56),
    CompanyBoard('Temporal', 'greenhouse', 'temporaltechnologies', 56),
    CompanyBoard('BeyondTrust', 'greenhouse', 'beyondtrust', 55),
    CompanyBoard('Mercury', 'greenhouse', 'mercury', 55),
    CompanyBoard('Writer', 'ashby', 'writer', 55),
    CompanyBoard('Mirantis', 'smartrecruiters', 'mirantis', 54),
    CompanyBoard('LinkedIn', 'greenhouse', 'linkedin', 53),
    CompanyBoard('Samsung Semiconductor', 'greenhouse', 'samsungsemiconductor', 52),
    CompanyBoard('Fastly', 'greenhouse', 'fastly', 51),
    CompanyBoard('Trellix', 'workday', 'trellix|wd1|EnterpriseCareers', 50),
    CompanyBoard('CME Group', 'workday', 'cmegroup|wd1|cme_careers', 49),
    CompanyBoard('Fireworks AI', 'ashby', 'fireworks', 49),
    CompanyBoard('Sentry', 'ashby', 'sentry', 48),
    CompanyBoard('Discord', 'greenhouse', 'discord', 47),
    CompanyBoard('Tenable', 'greenhouse', 'tenableinc', 47),
    CompanyBoard('Miro', 'ashby', 'miro', 46),
    CompanyBoard('Meesho', 'lever', 'meesho', 45),
    CompanyBoard('Marqeta', 'greenhouse', 'marqeta', 43),
    CompanyBoard('Neo4j', 'greenhouse', 'neo4j', 43),
    CompanyBoard('Silicon Labs', 'workday', 'silabs|wd1|SiliconlabsCareers', 43),
    CompanyBoard('Snorkel AI', 'greenhouse', 'snorkelai', 42),
    CompanyBoard('Runway', 'ashby', 'runway-ml', 41),
    CompanyBoard('Airtable', 'greenhouse', 'airtable', 40),
    CompanyBoard('Algolia', 'greenhouse', 'algolia', 40),
    CompanyBoard('Forcepoint', 'workday', 'forcepoint|wd1|external-careers', 40),
    CompanyBoard('Flow Traders', 'greenhouse', 'flowtraders', 38),
    CompanyBoard('Kyndryl', 'workday', 'kyndryl|wd5|KyndrylEarlyCareers', 38),
    CompanyBoard('Recorded Future', 'greenhouse', 'recordedfuture', 38),
    CompanyBoard('SingleStore', 'greenhouse', 'singlestore', 38),
    CompanyBoard('Supercell', 'ashby', 'supercell', 38),
    CompanyBoard('Dropbox', 'greenhouse', 'dropbox', 37),
    CompanyBoard('Uniphore', 'workday', 'uniphore|wd503|Uniphore', 37),
    CompanyBoard('BrowserStack', 'workday', 'browserstack|wd3|External', 36),
    CompanyBoard('LaunchDarkly', 'greenhouse', 'launchdarkly', 36),
    CompanyBoard('Agilent Technologies', 'workday', 'agilent|wd5|Agilent_Student_Careers', 35),
    CompanyBoard('Air India', 'greenhouse', 'air', 35),
    CompanyBoard('JFrog', 'greenhouse', 'jfrog', 35),
    CompanyBoard('Render', 'ashby', 'render', 34),
    CompanyBoard('Akuna Capital', 'greenhouse', 'akunacapital', 33),
    CompanyBoard('Confluent', 'ashby', 'confluent', 32),
    CompanyBoard('Modal Labs', 'ashby', 'modal', 31),
    CompanyBoard('Astronomer', 'ashby', 'astronomer', 29),
    CompanyBoard('Couchbase', 'greenhouse', 'couchbaseinc', 28),
    CompanyBoard('Hex Technologies', 'greenhouse', 'hextechnologies', 28),
    CompanyBoard('Armis', 'greenhouse', 'armissecurity', 27),
    CompanyBoard('Atomicwork', 'greenhouse', 'atomicwork', 27),
    CompanyBoard('Contentful', 'greenhouse', 'contentful', 27),
    CompanyBoard('Druva', 'greenhouse', 'druva', 27),
    CompanyBoard('Khan Academy', 'greenhouse', 'khanacademy', 27),
    CompanyBoard('Razorpay', 'greenhouse', 'razorpaysoftwareprivatelimited', 27),
    CompanyBoard('SUSE', 'workday', 'suse|wd3|Jobsatsuse', 27),
    CompanyBoard('Cockroach Labs', 'greenhouse', 'cockroachlabs', 26),
    CompanyBoard('Porter', 'lever', 'porter', 26),
    CompanyBoard('CloudSEK', 'greenhouse', 'cloudsek', 25),
    CompanyBoard('Linear', 'ashby', 'Linear', 25),
    CompanyBoard('Redis', 'ashby', 'redis', 25),
    CompanyBoard('Snyk', 'workday', 'snyk|wd103|External', 25),
    CompanyBoard('ExtraHop', 'greenhouse', 'extrahopnetworks', 24),
    CompanyBoard('Teleport', 'ashby', 'goteleport', 24),
    CompanyBoard('Zeta', 'lever', 'zeta', 23),
    CompanyBoard('RunPod', 'ashby', 'runpod', 22),
    CompanyBoard('MinIO', 'greenhouse', 'minio', 21),
    CompanyBoard('PagerDuty', 'greenhouse', 'pagerduty', 21),
    CompanyBoard('Dataiku', 'greenhouse', 'dataiku', 20),
    CompanyBoard('Graviton Research Capital', 'greenhouse', 'gravitonresearchcapital', 20),
    CompanyBoard('Anyscale', 'ashby', 'anyscale', 19),
    CompanyBoard('Coursera', 'greenhouse', 'coursera', 19),
    CompanyBoard('Observe.AI', 'greenhouse', 'observeai', 19),
    CompanyBoard('Five Rings', 'greenhouse', 'fiveringsllc', 18),
    CompanyBoard('Loft Labs', 'ashby', 'vClusterLabs', 17),
    CompanyBoard('NK Securities', 'greenhouse', 'nksecuritiesresearch', 17),
    CompanyBoard('Superside', 'lever', 'superside', 17),
    CompanyBoard('Honeycomb', 'greenhouse', 'honeycomb', 16),
    CompanyBoard('Rakuten Symphony', 'greenhouse', 'symphony', 16),
    CompanyBoard('Yugabyte', 'greenhouse', 'yugabyte', 16),
    CompanyBoard('Neon', 'lever', 'neon', 15),
    CompanyBoard('SigNoz', 'ashby', 'SigNoz', 15),
    CompanyBoard('Domino Data Lab', 'greenhouse', 'dominodatalab', 14),
    CompanyBoard('Ampere Computing', 'recruitee', 'ampere', 13),
    CompanyBoard('Quantum Corporation', 'ashby', 'quantum', 13),
    CompanyBoard('Starburst', 'greenhouse', 'starburst', 13),
    CompanyBoard('Udemy', 'greenhouse', 'udemy', 13),
    CompanyBoard('Apollo GraphQL', 'ashby', 'apollo-graphql', 12),
    CompanyBoard('Mercari India', 'workable', 'mercari-india', 11),
    CompanyBoard('Airbyte', 'ashby', 'airbyte', 10),
    CompanyBoard('Ataccama', 'lever', 'ataccama', 10),
    CompanyBoard('Bellatrix Aerospace', 'lever', 'aero', 10),
    CompanyBoard('Belvedere Trading', 'lever', 'belvederetrading', 10),
    CompanyBoard('Blue Dart', 'lever', 'blue', 10),
    CompanyBoard('DeepMind', 'greenhouse', 'deepmind', 10),
    CompanyBoard('Getty Images', 'lever', 'gettyimages', 10),
    CompanyBoard('Slack', 'workday', 'salesforce|wd12|Slack', 10),
    CompanyBoard('Sysdig', 'lever', 'sysdig', 10),
    CompanyBoard('Buildkite', 'greenhouse', 'buildkite', 9),
    CompanyBoard('Elsevier', 'greenhouse', 'elsevier', 9),
    CompanyBoard('Fi Money', 'lever', 'epifi', 9),
    CompanyBoard('Groww', 'greenhouse', 'groww', 9),
    CompanyBoard('PlanetScale', 'greenhouse', 'planetscale', 9),
    CompanyBoard('Target India', 'greenhouse', 'india', 9),
    CompanyBoard('AssemblyAI', 'greenhouse', 'assemblyai', 8),
    CompanyBoard('ClickHouse', 'ashby', 'langfuse', 8),
    CompanyBoard('Labelbox', 'greenhouse', 'labelbox', 8),
    CompanyBoard('PostHog', 'ashby', 'posthog', 8),
    CompanyBoard('Railway', 'ashby', 'railway', 8),
    CompanyBoard('Sourcegraph', 'greenhouse', 'sourcegraph91', 8),
    CompanyBoard('CircleCI', 'greenhouse', 'circleci', 7),
    CompanyBoard('GalaxEye', 'greenhouse', 'space', 7),
    CompanyBoard('Hugging Face', 'workable', 'huggingface', 7),
    CompanyBoard('Microchip Technology', 'smartrecruiters', 'microchip', 7),
    CompanyBoard('MotherDuck', 'ashby', 'MotherDuck', 7),
    CompanyBoard('National Instruments', 'greenhouse', 'national', 7),
    CompanyBoard('Navi', 'ashby', 'navi', 7),
    CompanyBoard('Pixxel', 'greenhouse', 'space', 7),
    CompanyBoard('ICON plc', 'ashby', 'icon', 6),
    CompanyBoard('Mend.io', 'ashby', 'mend-io', 6),
    CompanyBoard('Monte Carlo Data', 'ashby', 'montecarlodata', 6),
    CompanyBoard('Pinecone', 'ashby', 'pinecone', 6),
    CompanyBoard('SAS', 'greenhouse', 'sas', 6),
    CompanyBoard('Swiggy', 'smartrecruiters', 'swiggy', 6),
    CompanyBoard('Swiggy Instamart', 'smartrecruiters', 'swiggy', 6),
    CompanyBoard('Ventana Micro Systems', 'greenhouse', 'ventana', 6),
    CompanyBoard('Lightdash', 'ashby', 'lightdash', 5),
    CompanyBoard('Quora', 'ashby', 'quora', 5),
    CompanyBoard('Boston Consulting Group', 'greenhouse', 'bcg', 4),
    CompanyBoard('Logitech', 'lever', 'jobvite', 4),
    CompanyBoard('Tiger Analytics', 'ashby', 'tiger', 4),
    CompanyBoard('CRED', 'lever', 'cred', 3),
    CompanyBoard('Hudson River Trading', 'greenhouse', 'hrttalentcommunity', 3),
    CompanyBoard('IndiGo', 'greenhouse', 'indigo', 3),
    CompanyBoard('Netlify', 'greenhouse', 'netlify', 3),
    CompanyBoard('Tinybird', 'lever', 'tinybird', 3),
    CompanyBoard('Unacademy', 'smartrecruiters', 'unacademy', 3),
    CompanyBoard('ByteDance', 'smartrecruiters', 'bytedance', 2),
    CompanyBoard('Disney', 'greenhouse', 'disney', 2),
    CompanyBoard('Dremio', 'greenhouse', 'dremio', 2),
    CompanyBoard('InfluxData', 'ashby', 'Influxdata', 2),
    CompanyBoard("Lowe's India", 'greenhouse', 'talent', 2),
    CompanyBoard('Pine Labs', 'greenhouse', 'pine', 2),
    CompanyBoard('Remote', 'greenhouse', 'remote', 2),
    CompanyBoard('Standard Chartered', 'recruitee', 'standard', 2),
    CompanyBoard('Thales', 'smartrecruiters', 'thales', 2),
    CompanyBoard('TigerGraph', 'greenhouse', 'tigergraph', 2),
    CompanyBoard('Visa', 'smartrecruiters', 'visa', 2),
    CompanyBoard('Weaviate', 'ashby', 'weaviate', 2),
    CompanyBoard('X', 'smartrecruiters', 'x', 2),
    CompanyBoard('Cars24', 'smartrecruiters', 'cars24', 1),
    CompanyBoard('Eli Lilly', 'ashby', 'eli', 1),
    CompanyBoard('Glean', 'smartrecruiters', 'glean', 1),
    CompanyBoard('HiBob', 'smartrecruiters', 'hibob', 1),
    CompanyBoard('Huawei', 'lever', 'career', 1),
    CompanyBoard('Infosys', 'lever', 'career', 1),
    CompanyBoard('Kimberly-Clark', 'smartrecruiters', 'kimberlyclark', 1),
    CompanyBoard('Luxoft', 'lever', 'career', 1),
    CompanyBoard('Media.net', 'smartrecruiters', 'medianet', 1),
    CompanyBoard('Meta', 'recruitee', 'meta', 1),
    CompanyBoard('NoBroker', 'smartrecruiters', 'nobroker', 1),
    CompanyBoard('Siemens Energy', 'recruitee', 'siemensenergy', 1),
    CompanyBoard('Uber', 'smartrecruiters', 'uber', 1),
    CompanyBoard('Upstox', 'smartrecruiters', 'upstox', 1),
    CompanyBoard('Western Union', 'greenhouse', 'westernunion', 1),
    CompanyBoard('Whatfix', 'smartrecruiters', 'whatfix', 1),)


BOARDS_BY_PLATFORM: dict[str, tuple[CompanyBoard, ...]] = {
    platform: tuple(b for b in COMPANY_BOARDS if b.platform == platform)
    for platform in sorted({b.platform for b in COMPANY_BOARDS})
}
