#!/usr/bin/env bash
set -euo pipefail

if ! command -v gh >/dev/null 2>&1; then
  echo "gh CLI is required. Install GitHub CLI first." >&2
  exit 1
fi

if ! gh auth status >/dev/null 2>&1; then
  echo "gh CLI is not authenticated. Run: gh auth login" >&2
  exit 1
fi

REPO="${1:-${GITHUB_REPOSITORY:-}}"
if [ -z "${REPO}" ]; then
  echo "Usage: $0 <owner/repo>  (or set GITHUB_REPOSITORY)" >&2
  exit 1
fi

required_keys=(
  STAGING_PLAYWRIGHT_BASE_URL
  STAGING_PLAYWRIGHT_ADMIN_EMAIL
  STAGING_PLAYWRIGHT_ADMIN_PASSWORD
  STAGING_PLAYWRIGHT_EMPLOYER_EMAIL
  STAGING_PLAYWRIGHT_EMPLOYER_PASSWORD
  MONGODB_URL
  REDIS_URL
  ANALYTICS_WAREHOUSE_CLICKHOUSE_HOST
  ANALYTICS_WAREHOUSE_CLICKHOUSE_DATABASE
  ANALYTICS_WAREHOUSE_CLICKHOUSE_USERNAME
  ANALYTICS_WAREHOUSE_CLICKHOUSE_PASSWORD
  MLOPS_MODEL_ARTIFACT_S3_REGION
  MLOPS_MODEL_ARTIFACT_S3_ACCESS_KEY_ID
  MLOPS_MODEL_ARTIFACT_S3_SECRET_ACCESS_KEY
  MODEL_ARTIFACT_BUCKET
  ANALYTICS_BI_TOOL_URL
  GRAFANA_DS_DASHBOARD_URL
  GRAFANA_ADMIN_PASSWORD
  LLM_API_KEY
  GOOGLE_OAUTH_CLIENT_ID
  GOOGLE_OAUTH_CLIENT_SECRET
  SMTP_USER
  SMTP_PASSWORD
  MLOPS_ALERT_SLACK_WEBHOOK_URL
  MLOPS_ALERT_PAGERDUTY_ROUTING_KEY
  MLOPS_INCIDENT_DEFAULT_OWNER
  MLOPS_ONCALL_PRIMARY
  MLOPS_ONCALL_SECONDARY
)

for key in "${required_keys[@]}"; do
  if [ -z "${!key:-}" ]; then
    echo "Missing required env var: ${key}" >&2
    exit 1
  fi
done

echo "[ops] configuring GitHub secrets for ${REPO}"
gh secret set STAGING_PLAYWRIGHT_BASE_URL --repo "${REPO}" --body "${STAGING_PLAYWRIGHT_BASE_URL}"
gh secret set STAGING_PLAYWRIGHT_ADMIN_EMAIL --repo "${REPO}" --body "${STAGING_PLAYWRIGHT_ADMIN_EMAIL}"
gh secret set STAGING_PLAYWRIGHT_ADMIN_PASSWORD --repo "${REPO}" --body "${STAGING_PLAYWRIGHT_ADMIN_PASSWORD}"
gh secret set STAGING_PLAYWRIGHT_EMPLOYER_EMAIL --repo "${REPO}" --body "${STAGING_PLAYWRIGHT_EMPLOYER_EMAIL}"
gh secret set STAGING_PLAYWRIGHT_EMPLOYER_PASSWORD --repo "${REPO}" --body "${STAGING_PLAYWRIGHT_EMPLOYER_PASSWORD}"
gh secret set MONGODB_URL --repo "${REPO}" --body "${MONGODB_URL}"
gh secret set REDIS_URL --repo "${REPO}" --body "${REDIS_URL}"
gh variable set ANALYTICS_WAREHOUSE_CLICKHOUSE_HOST --repo "${REPO}" --body "${ANALYTICS_WAREHOUSE_CLICKHOUSE_HOST}"
gh variable set ANALYTICS_WAREHOUSE_CLICKHOUSE_DATABASE --repo "${REPO}" --body "${ANALYTICS_WAREHOUSE_CLICKHOUSE_DATABASE}"
gh secret set ANALYTICS_WAREHOUSE_CLICKHOUSE_USERNAME --repo "${REPO}" --body "${ANALYTICS_WAREHOUSE_CLICKHOUSE_USERNAME}"
gh secret set ANALYTICS_WAREHOUSE_CLICKHOUSE_PASSWORD --repo "${REPO}" --body "${ANALYTICS_WAREHOUSE_CLICKHOUSE_PASSWORD}"
gh variable set MLOPS_MODEL_ARTIFACT_S3_REGION --repo "${REPO}" --body "${MLOPS_MODEL_ARTIFACT_S3_REGION}"
gh secret set MLOPS_MODEL_ARTIFACT_S3_ACCESS_KEY_ID --repo "${REPO}" --body "${MLOPS_MODEL_ARTIFACT_S3_ACCESS_KEY_ID}"
gh secret set MLOPS_MODEL_ARTIFACT_S3_SECRET_ACCESS_KEY --repo "${REPO}" --body "${MLOPS_MODEL_ARTIFACT_S3_SECRET_ACCESS_KEY}"
gh variable set MODEL_ARTIFACT_BUCKET --repo "${REPO}" --body "${MODEL_ARTIFACT_BUCKET}"
gh variable set ANALYTICS_BI_TOOL_URL --repo "${REPO}" --body "${ANALYTICS_BI_TOOL_URL}"
gh variable set GRAFANA_DS_DASHBOARD_URL --repo "${REPO}" --body "${GRAFANA_DS_DASHBOARD_URL}"
gh secret set GRAFANA_ADMIN_PASSWORD --repo "${REPO}" --body "${GRAFANA_ADMIN_PASSWORD}"
gh secret set LLM_API_KEY --repo "${REPO}" --body "${LLM_API_KEY}"
gh secret set GOOGLE_OAUTH_CLIENT_ID --repo "${REPO}" --body "${GOOGLE_OAUTH_CLIENT_ID}"
gh secret set GOOGLE_OAUTH_CLIENT_SECRET --repo "${REPO}" --body "${GOOGLE_OAUTH_CLIENT_SECRET}"
gh secret set SMTP_USER --repo "${REPO}" --body "${SMTP_USER}"
gh secret set SMTP_PASSWORD --repo "${REPO}" --body "${SMTP_PASSWORD}"
gh secret set MLOPS_ALERT_SLACK_WEBHOOK_URL --repo "${REPO}" --body "${MLOPS_ALERT_SLACK_WEBHOOK_URL}"
gh secret set MLOPS_ALERT_PAGERDUTY_ROUTING_KEY --repo "${REPO}" --body "${MLOPS_ALERT_PAGERDUTY_ROUTING_KEY}"
gh variable set MLOPS_INCIDENT_DEFAULT_OWNER --repo "${REPO}" --body "${MLOPS_INCIDENT_DEFAULT_OWNER}"
gh variable set MLOPS_ONCALL_PRIMARY --repo "${REPO}" --body "${MLOPS_ONCALL_PRIMARY}"
gh variable set MLOPS_ONCALL_SECONDARY --repo "${REPO}" --body "${MLOPS_ONCALL_SECONDARY}"

echo "[ops] secrets/vars configured"
