export type EducationProgramOption = {
  value: string;
  label: string;
  group: string;
};

const CORE_FIELDS = [
  "Accounting & Commerce",
  "Actuarial Science",
  "Advertising",
  "Aerospace Engineering",
  "Agriculture",
  "Agricultural Business and Management",
  "Agricultural Economics",
  "Agricultural Education",
  "Agricultural Engineering",
  "Agricultural Journalism",
  "Agricultural Mechanization",
  "Agronomy and Crop Science",
  "Air Traffic Control",
  "Anatomy",
  "Animation and Special Effects",
  "Anthropology",
  "Applied Mathematics",
  "Applied Physics",
  "Aquaculture",
  "Architecture",
  "Art",
  "Art Education",
  "Art History",
  "Artificial Intelligence",
  "Artificial Intelligence and Robotics",
  "Astronomy",
  "Astrophysics",
  "Athletic Training",
  "Atmospheric Science",
  "Automotive Engineering",
  "Aviation",
  "Bakery Science",
  "Biochemistry",
  "Bioethics",
  "Biology",
  "Biomedical Engineering",
  "Biomedical Science",
  "Biopsychology",
  "Biotechnology",
  "Botany/Plant Biology",
  "Business Administration/Management",
  "Business Analytics",
  "Business Communications",
  "Cell Biology",
  "Ceramic Engineering",
  "Chemical Engineering",
  "Chemical Physics",
  "Cinematography and Film/Video Production",
  "Civil Engineering",
  "Clinical Psychology",
  "Cognitive Psychology",
  "Communication Disorders",
  "Communications Studies",
  "Comparative Literature",
  "Computational Biology",
  "Computer and Information Science",
  "Computer Engineering",
  "Computer Graphics",
  "Computer Science",
  "Construction Management",
  "Counseling",
  "Creative Writing",
  "Criminal Science",
  "Criminology",
  "Culinary Arts",
  "Cyber Security",
  "Data Processing",
  "Data Science",
  "Dental Hygiene",
  "Design Management",
  "Development Communication",
  "Diagnostic Medical Sonography",
  "Dietetics",
  "Digital Communications and Media/Multimedia",
  "Drawing",
  "Early Childhood Education",
  "Economics",
  "Education",
  "Education Administration",
  "Educational Psychology",
  "Electrical Engineering",
  "Electronics and Instrumentation",
  "Electronics and Telecommunication",
  "English",
  "English Literature",
  "Entomology",
  "Environmental Science",
  "Finance",
  "Food Science",
  "Forensic Science",
  "Game Design",
  "Geography",
  "Geology",
  "Graphic Design",
  "Healthcare Management",
  "History",
  "Hospitality Management",
  "Human Resources",
  "Information Technology",
  "International Relations",
  "Journalism",
  "Law",
  "Linguistics",
  "Management",
  "Marketing",
  "Mass Communication",
  "Mathematics",
  "Mechanical Engineering",
  "Microbiology",
  "Nursing",
  "Operations",
  "Pharmacy",
  "Philosophy",
  "Physics",
  "Political Science",
  "Product Management",
  "Psychology",
  "Public Administration",
  "Robotics",
  "Social Work",
  "Sociology",
  "Software Engineering",
  "Statistics",
  "Strategy",
  "Tourism Management",
  "UI/UX Design",
  "Zoology",
];

const REQUESTED_FIELD_OPTIONS = [
  "Computer Science Engineering (CSE)",
  "Information Technology (IT)",
  "Software Engineering",
  "Computer Engineering",
  "Computer Science & Design",
  "Computer Science & Business Systems",
  "Artificial Intelligence",
  "Artificial Intelligence & Machine Learning",
  "AI & ML",
  "Machine Learning",
  "Data Science",
  "Big Data Analytics",
  "Cyber Security",
  "Information Security",
  "Cloud Computing",
  "Blockchain Technology",
  "Internet of Things (IoT)",
  "IoT",
  "Full Stack Development",
  "DevOps",
  "Quantum Computing",
  "Human Computer Interaction",
  "Gaming Technology",
  "Electronics & Communication Engineering",
  "Electronics Engineering",
  "Electronics & Instrumentation Engineering",
  "VLSI Design",
  "Embedded Systems",
  "Semiconductor Technology",
  "Microelectronics",
  "Communication Engineering",
  "Signal Processing",
  "Electrical Engineering",
  "Electrical & Electronics Engineering",
  "Power Engineering",
  "Renewable Energy Engineering",
  "Energy Engineering",
  "Smart Grid Technology",
  "Mechanical Engineering",
  "Mechatronics",
  "Robotics & Automation",
  "Manufacturing Engineering",
  "Industrial Engineering",
  "Production Engineering",
  "Tool Engineering",
  "Civil Engineering",
  "Structural Engineering",
  "Construction Engineering",
  "Transportation Engineering",
  "Environmental Engineering",
  "Geotechnical Engineering",
  "Chemical Engineering",
  "Petrochemical Engineering",
  "Petroleum Engineering",
  "Polymer Engineering",
  "Paint Technology",
  "Aerospace Engineering",
  "Aeronautical Engineering",
  "Avionics Engineering",
  "Space Technology",
  "Biotechnology",
  "Biomedical Engineering",
  "Genetic Engineering",
  "Bioinformatics",
  "Biochemical Engineering",
  "Agricultural Engineering",
  "Food Technology",
  "Dairy Technology",
  "Food Engineering",
  "Mining Engineering",
  "Metallurgical Engineering",
  "Ceramic Engineering",
  "Textile Engineering",
  "Leather Technology",
  "Marine Engineering",
  "Naval Architecture",
  "Automobile Engineering",
  "Printing Technology",
  "Fire & Safety Engineering",
  "Physics",
  "Chemistry",
  "Mathematics",
  "Statistics",
  "Computer Science",
  "Microbiology",
  "Genetics",
  "Zoology",
  "Botany",
  "Biochemistry",
  "Environmental Science",
  "Forensic Science",
  "Agriculture",
  "Forestry",
  "Fisheries Science",
  "Food Science",
  "Nutrition & Dietetics",
  "Geology",
  "Geography",
  "Oceanography",
  "Meteorology",
  "Psychology",
  "Economics",
  "Anthropology",
  "Hospitality & Hotel Administration",
  "Animation",
  "Multimedia",
  "General BCA",
  "General Management",
  "Marketing",
  "Finance",
  "Human Resources",
  "Business Analytics",
  "Digital Marketing",
  "International Business",
  "Entrepreneurship",
  "Retail Management",
  "Logistics & Supply Chain",
  "FinTech",
  "Family Business",
  "General",
  "Accounting",
  "Banking",
  "Insurance",
  "Taxation",
  "Financial Markets",
  "Investment Management",
  "E-Commerce",
  "English",
  "Sociology",
  "Political Science",
  "History",
  "Philosophy",
  "Public Administration",
  "Journalism",
  "Mass Communication",
  "International Relations",
  "Linguistics",
  "Education",
  "Social Work",
  "Operations",
  "Data Analytics",
  "Product Management",
  "Healthcare Management",
  "Hospital Administration",
  "Aviation Management",
  "Tourism Management",
  "Event Management",
  "Agri-Business",
  "Strategy",
  "Sustainability Management",
  "Power Systems",
  "Thermal Engineering",
  "Manufacturing Systems",
  "General Medicine",
  "General Surgery",
  "Pediatrics",
  "Dermatology",
  "Psychiatry",
  "Radiology",
  "Anesthesiology",
  "Orthopedics",
  "Ophthalmology",
  "ENT",
  "Obstetrics & Gynecology",
  "Pathology",
  "Pharmacology",
  "Community Medicine",
  "Cardiology",
  "Neurology",
  "Nephrology",
  "Oncology",
  "Gastroenterology",
  "Endocrinology",
  "Pulmonology",
  "Urology",
  "Neurosurgery",
  "Plastic Surgery",
  "Corporate Law",
  "Criminal Law",
  "Constitutional Law",
  "Cyber Law",
  "Intellectual Property Law",
  "International Law",
  "Taxation Law",
  "Environmental Law",
  "Human Rights Law",
  "Labour Law",
  "Business Law",
  "UI/UX Design",
  "Product Design",
  "Fashion Design",
  "Graphic Design",
  "Animation Design",
  "Interior Design",
  "Communication Design",
  "Game Design",
  "Industrial Design",
  "Transportation Design",
  "Agronomy",
  "Horticulture",
  "Soil Science",
  "Plant Pathology",
  "Agricultural Economics",
  "Genetics & Plant Breeding",
  "Entomology",
  "Agricultural Extension",
  "Hotel Management",
  "Culinary Arts",
  "Hospitality Operations",
  "Food Production",
  "Front Office Management",
  "Generative AI",
  "Agentic AI",
  "AI Engineering",
  "Prompt Engineering",
  "Responsible AI",
  "Quantum Information Science",
  "Semiconductor Engineering",
  "EV Technology",
  "Autonomous Systems",
  "AR/VR Engineering",
  "XR Design",
  "Climate Technology",
  "Green Energy Systems",
  "Digital Health Informatics",
  "Computational Biology",
];

const ENGINEERING_FIELDS = [
  "Computer Science Engineering (CSE)",
  "Information Technology (IT)",
  "Software Engineering",
  "Computer Engineering",
  "Computer Science & Design",
  "Computer Science & Business Systems",
  "Artificial Intelligence",
  "Artificial Intelligence & Machine Learning",
  "Machine Learning",
  "Data Science",
  "Big Data Analytics",
  "Cyber Security",
  "Information Security",
  "Cloud Computing",
  "Blockchain Technology",
  "Internet of Things (IoT)",
  "IoT",
  "Full Stack Development",
  "DevOps",
  "Quantum Computing",
  "Human Computer Interaction",
  "Gaming Technology",
  "Electronics & Communication Engineering",
  "Electronics Engineering",
  "Electronics & Instrumentation Engineering",
  "VLSI Design",
  "Embedded Systems",
  "Semiconductor Technology",
  "Microelectronics",
  "Communication Engineering",
  "Signal Processing",
  "Electrical Engineering",
  "Electrical & Electronics Engineering",
  "Power Engineering",
  "Renewable Energy Engineering",
  "Energy Engineering",
  "Smart Grid Technology",
  "Mechanical Engineering",
  "Mechatronics",
  "Robotics & Automation",
  "Manufacturing Engineering",
  "Industrial Engineering",
  "Production Engineering",
  "Tool Engineering",
  "Civil Engineering",
  "Structural Engineering",
  "Construction Engineering",
  "Transportation Engineering",
  "Environmental Engineering",
  "Geotechnical Engineering",
  "Chemical Engineering",
  "Petrochemical Engineering",
  "Petroleum Engineering",
  "Polymer Engineering",
  "Paint Technology",
  "Aerospace Engineering",
  "Aeronautical Engineering",
  "Avionics Engineering",
  "Space Technology",
  "Biotechnology",
  "Biomedical Engineering",
  "Genetic Engineering",
  "Bioinformatics",
  "Biochemical Engineering",
  "Agricultural Engineering",
  "Food Technology",
  "Dairy Technology",
  "Food Engineering",
  "Mining Engineering",
  "Metallurgical Engineering",
  "Ceramic Engineering",
  "Textile Engineering",
  "Leather Technology",
  "Marine Engineering",
  "Naval Architecture",
  "Automobile Engineering",
  "Printing Technology",
  "Fire & Safety Engineering",
];

const SCIENCE_FIELDS = [
  "Physics",
  "Chemistry",
  "Mathematics",
  "Statistics",
  "Computer Science",
  "Data Science",
  "Artificial Intelligence",
  "Biotechnology",
  "Microbiology",
  "Genetics",
  "Zoology",
  "Botany",
  "Biochemistry",
  "Environmental Science",
  "Forensic Science",
  "Agriculture",
  "Forestry",
  "Fisheries Science",
  "Food Science",
  "Nutrition & Dietetics",
  "Geology",
  "Geography",
  "Oceanography",
  "Meteorology",
  "Psychology",
  "Economics",
  "Anthropology",
  "Hospitality & Hotel Administration",
  "Animation",
  "Multimedia",
];

const BCA_FIELDS = [
  "General BCA",
  "Data Science",
  "AI & ML",
  "Cloud Computing",
  "Cyber Security",
  "Full Stack Development",
  "Blockchain",
  "IoT",
  "Internet of Things (IoT)",
];

const BUSINESS_FIELDS = [
  "General Management",
  "Marketing",
  "Finance",
  "Human Resources",
  "Business Analytics",
  "Data Analytics",
  "Digital Marketing",
  "International Business",
  "Entrepreneurship",
  "Retail Management",
  "Logistics & Supply Chain",
  "FinTech",
  "Family Business",
  "Operations",
  "Product Management",
  "Healthcare Management",
  "Hospital Administration",
  "Aviation Management",
  "Tourism Management",
  "Event Management",
  "Agri-Business",
  "Information Technology",
  "Strategy",
  "Sustainability Management",
];

const COMMERCE_FIELDS = [
  "General",
  "Accounting",
  "Finance",
  "Banking",
  "Insurance",
  "Taxation",
  "Financial Markets",
  "Investment Management",
  "E-Commerce",
];

const ARTS_FIELDS = [
  "English",
  "Economics",
  "Psychology",
  "Sociology",
  "Political Science",
  "History",
  "Geography",
  "Philosophy",
  "Public Administration",
  "Journalism",
  "Mass Communication",
  "International Relations",
  "Linguistics",
  "Education",
  "Social Work",
];

const MEDICAL_FIELDS = [
  "General Medicine",
  "General Surgery",
  "Pediatrics",
  "Dermatology",
  "Psychiatry",
  "Radiology",
  "Anesthesiology",
  "Orthopedics",
  "Ophthalmology",
  "ENT",
  "Obstetrics & Gynecology",
  "Pathology",
  "Microbiology",
  "Pharmacology",
  "Community Medicine",
  "Cardiology",
  "Neurology",
  "Nephrology",
  "Oncology",
  "Gastroenterology",
  "Endocrinology",
  "Pulmonology",
  "Urology",
  "Neurosurgery",
  "Plastic Surgery",
  "Dentistry",
  "Nursing",
  "Physiotherapy",
  "Ayurveda",
  "Homeopathy",
  "Unani Medicine",
  "Pharmacy",
];

const LAW_FIELDS = [
  "Corporate Law",
  "Criminal Law",
  "Constitutional Law",
  "Cyber Law",
  "Intellectual Property Law",
  "International Law",
  "Taxation Law",
  "Environmental Law",
  "Human Rights Law",
  "Labour Law",
  "Business Law",
];

const DESIGN_FIELDS = [
  "UI/UX Design",
  "Product Design",
  "Fashion Design",
  "Graphic Design",
  "Animation Design",
  "Interior Design",
  "Communication Design",
  "Game Design",
  "Industrial Design",
  "Transportation Design",
];

const AGRICULTURE_FIELDS = [
  "Agronomy",
  "Horticulture",
  "Soil Science",
  "Plant Pathology",
  "Agricultural Economics",
  "Genetics & Plant Breeding",
  "Entomology",
  "Agricultural Extension",
  "Agricultural Engineering",
  "Food Technology",
  "Dairy Technology",
];

const HOSPITALITY_FIELDS = [
  "Hotel Management",
  "Culinary Arts",
  "Tourism Management",
  "Hospitality Operations",
  "Food Production",
  "Front Office Management",
];

const EMERGING_FIELDS = [
  "Generative AI",
  "Agentic AI",
  "AI Engineering",
  "Prompt Engineering",
  "Responsible AI",
  "Quantum Information Science",
  "Semiconductor Engineering",
  "EV Technology",
  "Autonomous Systems",
  "AR/VR Engineering",
  "XR Design",
  "Climate Technology",
  "Green Energy Systems",
  "Digital Health Informatics",
  "Computational Biology",
];

export const EDUCATION_PROGRAM_OPTIONS: EducationProgramOption[] = [
  { value: "anm", label: "ANM (Auxiliary Nursing Midwifery)", group: "Diploma & Certificate" },
  { value: "gnm", label: "GNM (General Nursing and Midwifery)", group: "Diploma & Certificate" },
  { value: "dmlt", label: "DMLT (Diploma in Medical Laboratory Technology)", group: "Diploma & Certificate" },
  { value: "dpharm", label: "D.Pharm (Diploma in Pharmacy)", group: "Diploma & Certificate" },
  { value: "deled", label: "D.El.Ed (Diploma in Elementary Education)", group: "Diploma & Certificate" },
  { value: "diploma_engineering", label: "Diploma in Engineering", group: "Diploma & Certificate" },
  { value: "iti", label: "ITI Certificate (Industrial Training Institute Certificate)", group: "Diploma & Certificate" },
  { value: "ba", label: "B.A. (Bachelor of Arts)", group: "Undergraduate" },
  { value: "bsc", label: "B.Sc. (Bachelor of Science)", group: "Undergraduate" },
  { value: "bcom", label: "B.Com. (Bachelor of Commerce)", group: "Undergraduate" },
  { value: "btech", label: "B.Tech (Bachelor of Technology)", group: "Undergraduate" },
  { value: "be", label: "B.E. (Bachelor of Engineering)", group: "Undergraduate" },
  { value: "bca", label: "BCA (Bachelor of Computer Applications)", group: "Undergraduate" },
  { value: "bba", label: "BBA (Bachelor of Business Administration)", group: "Undergraduate" },
  { value: "barch", label: "B.Arch (Bachelor of Architecture)", group: "Undergraduate" },
  { value: "bdes", label: "B.Des (Bachelor of Design)", group: "Undergraduate" },
  { value: "bpharm", label: "B.Pharm (Bachelor of Pharmacy)", group: "Undergraduate" },
  { value: "bds", label: "BDS (Bachelor of Dental Surgery)", group: "Undergraduate" },
  { value: "mbbs", label: "MBBS (Bachelor of Medicine and Bachelor of Surgery)", group: "Undergraduate" },
  { value: "bhms", label: "BHMS (Bachelor of Homeopathic Medicine and Surgery)", group: "Undergraduate" },
  { value: "bams", label: "BAMS (Bachelor of Ayurvedic Medicine and Surgery)", group: "Undergraduate" },
  { value: "bums", label: "BUMS (Bachelor of Unani Medicine and Surgery)", group: "Undergraduate" },
  { value: "bnys", label: "BNYS (Bachelor of Naturopathy and Yogic Sciences)", group: "Undergraduate" },
  { value: "bpt", label: "BPT (Bachelor of Physiotherapy)", group: "Undergraduate" },
  { value: "bsc_nursing", label: "B.Sc Nursing (Bachelor of Science in Nursing)", group: "Undergraduate" },
  { value: "bvsc", label: "B.V.Sc & AH (Bachelor of Veterinary Science and Animal Husbandry)", group: "Undergraduate" },
  { value: "bhm", label: "BHM (Bachelor of Hotel Management)", group: "Undergraduate" },
  { value: "bfa", label: "BFA (Bachelor of Fine Arts)", group: "Undergraduate" },
  { value: "bsw", label: "BSW (Bachelor of Social Work)", group: "Undergraduate" },
  { value: "blisc", label: "BLISc (Bachelor of Library and Information Science)", group: "Undergraduate" },
  { value: "bvoc", label: "B.Voc (Bachelor of Vocation)", group: "Undergraduate" },
  { value: "llb", label: "LLB (Bachelor of Laws)", group: "Law" },
  { value: "ba_llb", label: "BA LLB (Bachelor of Arts and Bachelor of Laws)", group: "Law" },
  { value: "bba_llb", label: "BBA LLB (Bachelor of Business Administration and Bachelor of Laws)", group: "Law" },
  { value: "bcom_llb", label: "B.Com LLB (Bachelor of Commerce and Bachelor of Laws)", group: "Law" },
  { value: "bsc_llb", label: "B.Sc LLB (Bachelor of Science and Bachelor of Laws)", group: "Law" },
  { value: "postgraduate", label: "Postgraduate (PG)", group: "Postgraduate" },
  { value: "ma", label: "M.A. (Master of Arts)", group: "Postgraduate" },
  { value: "msc", label: "M.Sc. (Master of Science)", group: "Postgraduate" },
  { value: "mcom", label: "M.Com. (Master of Commerce)", group: "Postgraduate" },
  { value: "mtech", label: "M.Tech (Master of Technology)", group: "Postgraduate" },
  { value: "me", label: "M.E. (Master of Engineering)", group: "Postgraduate" },
  { value: "mca", label: "MCA (Master of Computer Applications)", group: "Postgraduate" },
  { value: "mba", label: "MBA (Master of Business Administration)", group: "Postgraduate" },
  { value: "march", label: "M.Arch (Master of Architecture)", group: "Postgraduate" },
  { value: "mdes", label: "M.Des (Master of Design)", group: "Postgraduate" },
  { value: "mpharm", label: "M.Pharm (Master of Pharmacy)", group: "Postgraduate" },
  { value: "mpt", label: "MPT (Master of Physiotherapy)", group: "Postgraduate" },
  { value: "mds", label: "MDS (Master of Dental Surgery)", group: "Postgraduate" },
  { value: "md", label: "MD (Doctor of Medicine)", group: "Postgraduate" },
  { value: "ms", label: "MS (Master of Surgery)", group: "Postgraduate" },
  { value: "med", label: "M.Ed (Master of Education)", group: "Postgraduate" },
  { value: "msw", label: "MSW (Master of Social Work)", group: "Postgraduate" },
  { value: "mlisc", label: "M.Lib / MLISc (Master of Library and Information Science)", group: "Postgraduate" },
  { value: "llm", label: "LLM (Master of Laws)", group: "Law" },
  { value: "msc_nursing", label: "M.Sc Nursing (Master of Science in Nursing)", group: "Postgraduate" },
  { value: "pg_diploma", label: "PG Diploma (Postgraduate Diploma)", group: "Postgraduate" },
  { value: "mphil", label: "M.Phil (Master of Philosophy)", group: "Research & Doctoral" },
  { value: "phd", label: "Ph.D. (Doctor of Philosophy)", group: "Research & Doctoral" },
  { value: "dm", label: "DM (Doctorate of Medicine)", group: "Research & Doctoral" },
  { value: "mch", label: "M.Ch (Master of Chirurgiae)", group: "Research & Doctoral" },
  { value: "pharmd", label: "Pharm.D (Doctor of Pharmacy)", group: "Professional Programs" },
  { value: "ca", label: "CA (Chartered Accountant)", group: "Professional Programs" },
  { value: "cs", label: "CS (Company Secretary)", group: "Professional Programs" },
  { value: "cma", label: "CMA (Cost and Management Accountant)", group: "Professional Programs" },
  { value: "integrated_btech_mtech", label: "Integrated B.Tech + M.Tech", group: "Integrated Programs" },
  { value: "integrated_bsc_msc", label: "Integrated B.Sc + M.Sc", group: "Integrated Programs" },
  { value: "integrated_ba_ma", label: "Integrated BA + MA", group: "Integrated Programs" },
  { value: "integrated_bba_mba", label: "Integrated BBA + MBA", group: "Integrated Programs" },
  { value: "integrated_bca_mca", label: "Integrated BCA + MCA", group: "Integrated Programs" },
  { value: "integrated_llb", label: "Integrated LLB Programs", group: "Integrated Programs" },
  { value: "integrated_mtech", label: "Integrated M.Tech", group: "Integrated Programs" },
  { value: "integrated_msc", label: "Integrated M.Sc", group: "Integrated Programs" },
  { value: "mres", label: "M.Res (Master of Research)", group: "Research & Doctoral" },
  { value: "dsc", label: "D.Sc (Doctor of Science)", group: "Research & Doctoral" },
  { value: "dlitt", label: "D.Litt (Doctor of Letters)", group: "Research & Doctoral" },
];

export const EDUCATION_PROGRAM_GROUPS = Array.from(new Set(EDUCATION_PROGRAM_OPTIONS.map((item) => item.group)));

const FIELD_OPTIONS_BY_PROGRAM: Record<string, string[]> = {
  btech: [...ENGINEERING_FIELDS, ...EMERGING_FIELDS],
  be: [...ENGINEERING_FIELDS, ...EMERGING_FIELDS],
  diploma_engineering: [...ENGINEERING_FIELDS, ...EMERGING_FIELDS],
  mtech: [...ENGINEERING_FIELDS, "Power Systems", "Thermal Engineering", "Manufacturing Systems", ...EMERGING_FIELDS],
  me: [...ENGINEERING_FIELDS, "Power Systems", "Thermal Engineering", "Manufacturing Systems", ...EMERGING_FIELDS],
  integrated_btech_mtech: [...ENGINEERING_FIELDS, "Power Systems", "Thermal Engineering", "Manufacturing Systems", ...EMERGING_FIELDS],
  integrated_mtech: [...ENGINEERING_FIELDS, "Power Systems", "Thermal Engineering", "Manufacturing Systems", ...EMERGING_FIELDS],
  bsc: SCIENCE_FIELDS,
  msc: [...SCIENCE_FIELDS, ...EMERGING_FIELDS],
  integrated_bsc_msc: [...SCIENCE_FIELDS, ...EMERGING_FIELDS],
  integrated_msc: [...SCIENCE_FIELDS, ...EMERGING_FIELDS],
  bca: [...BCA_FIELDS, ...EMERGING_FIELDS],
  mca: [...BCA_FIELDS, "Software Engineering", ...EMERGING_FIELDS],
  integrated_bca_mca: [...BCA_FIELDS, ...EMERGING_FIELDS],
  bba: BUSINESS_FIELDS,
  mba: BUSINESS_FIELDS,
  integrated_bba_mba: BUSINESS_FIELDS,
  bcom: COMMERCE_FIELDS,
  mcom: COMMERCE_FIELDS,
  ba: ARTS_FIELDS,
  ma: ARTS_FIELDS,
  integrated_ba_ma: ARTS_FIELDS,
  mbbs: MEDICAL_FIELDS,
  md: MEDICAL_FIELDS,
  ms: MEDICAL_FIELDS,
  dm: MEDICAL_FIELDS,
  mch: MEDICAL_FIELDS,
  bds: MEDICAL_FIELDS,
  mds: MEDICAL_FIELDS,
  bpharm: MEDICAL_FIELDS,
  mpharm: MEDICAL_FIELDS,
  pharmd: MEDICAL_FIELDS,
  bhms: MEDICAL_FIELDS,
  bams: MEDICAL_FIELDS,
  bums: MEDICAL_FIELDS,
  bnys: MEDICAL_FIELDS,
  bpt: MEDICAL_FIELDS,
  mpt: MEDICAL_FIELDS,
  bsc_nursing: MEDICAL_FIELDS,
  msc_nursing: MEDICAL_FIELDS,
  gnm: MEDICAL_FIELDS,
  anm: MEDICAL_FIELDS,
  dmlt: MEDICAL_FIELDS,
  dpharm: MEDICAL_FIELDS,
  llb: LAW_FIELDS,
  llm: LAW_FIELDS,
  ba_llb: LAW_FIELDS,
  bba_llb: LAW_FIELDS,
  bcom_llb: LAW_FIELDS,
  bsc_llb: LAW_FIELDS,
  integrated_llb: LAW_FIELDS,
  bdes: DESIGN_FIELDS,
  mdes: DESIGN_FIELDS,
  barch: ["Architecture", "Architectural Engineering", "Architectural History", "Urban Planning", "Interior Design", "Landscape Architecture"],
  march: ["Architecture", "Architectural Engineering", "Urban Planning", "Landscape Architecture", "Sustainable Architecture"],
  bvsc: ["Veterinary Science", "Animal Husbandry", "Animal Science", "Dairy Technology", "Livestock Production"],
  bhm: HOSPITALITY_FIELDS,
  bfa: ["Fine Arts", "Painting", "Sculpture", "Applied Arts", "Visual Communication", "Art History", "Animation"],
  bsw: ["Social Work", "Community Development", "Public Policy", "Human Rights", "Development Communication"],
  msw: ["Social Work", "Community Development", "Public Policy", "Human Rights", "Development Communication"],
  blisc: ["Library Science", "Information Science", "Knowledge Management", "Digital Libraries"],
  mlisc: ["Library Science", "Information Science", "Knowledge Management", "Digital Libraries"],
  bvoc: ["Vocational Studies", "Retail Management", "Hospitality Operations", "Healthcare", "Software Development", "Automotive Technology"],
  ca: COMMERCE_FIELDS,
  cs: ["Corporate Law", "Governance", "Business Law", "Compliance", "Finance"],
  cma: COMMERCE_FIELDS,
};

function uniqueSorted(values: string[]): string[] {
  return Array.from(new Set(values.map((item) => item.trim()).filter(Boolean))).sort((a, b) => a.localeCompare(b));
}

export function getProgramValueFromLabel(label: string): string {
  const normalized = label.trim().toLowerCase();
  return EDUCATION_PROGRAM_OPTIONS.find((item) => item.label.toLowerCase() === normalized)?.value ?? "";
}

export function getFieldOfStudyOptions(courseLabel: string, domain: string): string[] {
  const programValue = getProgramValueFromLabel(courseLabel);
  const programFields = FIELD_OPTIONS_BY_PROGRAM[programValue] ?? [];
  const normalizedDomain = domain.trim().toLowerCase();
  const domainFields = (() => {
    switch (normalizedDomain) {
      case "engineering":
        return ENGINEERING_FIELDS;
      case "management":
        return BUSINESS_FIELDS;
      case "arts & science":
        return [...ARTS_FIELDS, ...SCIENCE_FIELDS, ...COMMERCE_FIELDS];
      case "medicine":
        return MEDICAL_FIELDS;
      case "law":
        return LAW_FIELDS;
      default:
        return [];
    }
  })();
  return uniqueSorted([
    ...programFields,
    ...domainFields,
    ...REQUESTED_FIELD_OPTIONS,
    ...AGRICULTURE_FIELDS,
    ...CORE_FIELDS,
    ...EMERGING_FIELDS,
  ]);
}
